### ISSUE TITLE
Error when checking for updates (SSL/TLS)

### ISSUE THREAD

**Issue by elisimpson** [leonsoft-kras/transmisson-remote-gui#1001]
Windows zip version. Message is "Error checking for new version. SSL/TLS support is not compiled."

**Comment by leonsoft-kras** [comment]
You will run the installation "transgui-5.9-setup.exe".

Zip version was created for "super-smart" people. To work with SSL / TLS in the program folder there are libraries ssleay32, libeay32. For successful work of libraries, "Visual C ++ Redistributable for Visual Studio 2008" should be installed, but you did not install it.

**Comment by elisimpson** [comment]
Thanks I'll install the extra lib.
