### ISSUE TITLE
Menu and toolbar hiding settings are not persistent

### ISSUE THREAD

**Issue by neuro18** [leonsoft-kras/transmisson-remote-gui#1004]
Hi,

Menu and toolbar hiding options you introduced in version 5.9 work only within a session. Need to store (and read) them in transgui.ini file also.

**Comment by leonsoft-kras** [comment]
fixed

**Comment by PeterDaveHello** [comment]
https://github.com/leonsoft-kras/transmisson-remote-gui/releases/tag/v5.10.0
