### ISSUE TITLE
Not working in MacOS 10.13 

### ISSUE THREAD

**Issue by bjornh84** [leonsoft-kras/transmisson-remote-gui#1006]
It won't start in MacOS 10.13 beta, not sure but I think it worked until beta 6 or 7.
Now nothing happens when i try to start the application.

**Comment by PeterDaveHello** [comment]
@bjornh84 the stable version of v10.13 will be released few days later, would you like to test the latest transgui on the latest macOS later? Thanks!

**Comment by bjornh84** [comment]
Yea, i know, I'm on GM now and usually its the same as official release.
Sure ill try it out, of course, anything to be able to download without having to VNC my media server :)

**Comment by PeterDaveHello** [comment]
I'll also test it once it's released 👍

**Comment by PeterDaveHello** [comment]
I got no problem to run Transgui v5.10 Build ec53346 on macOS 10.13 17A365.

**Comment by rrolandd** [comment]
It works fine on High Sierra for me too. Thanks!

Here is what does not work on High Sierra: https://sourceforge.net/projects/transgui/

**Comment by PeterDaveHello** [comment]
Looks like we can close it now. Thanks @rrolandd
