### ISSUE TITLE
Connection Time out too quick

### ISSUE THREAD

**Issue by rd1** [leonsoft-kras/transmisson-remote-gui#1007]
i get frequent connection time outs when i move my finished torrents to a slower nas, would it be possible to allow more time before signaling a time out to the user ?

or if the server sets a "busy" flag/register, TRG could check that instead of just thinking its a connection timeout ?

either way i'd like to reduce how low the timeout is , is there a way in the ini file or would that have to happen by programming ?

**Comment by leonsoft-kras** [comment]
while it is not clear.
what message appears on the screen?

**Comment by PeterDaveHello** [comment]
I think it's just connection timeout and @rd1 would like to change the timeout limit or add a status "busy" before timeout.

**Comment by rd1** [comment]
exactly. i thought it was perfectly  clear.

![timeout](https://user-images.githubusercontent.com/1567489/30381564-c0643a1e-986a-11e7-8936-44b449520eb0.PNG)

**Comment by leonsoft-kras** [comment]
I can't guess which messages are shown on a million operating systems and storage systems. 
it is better to ask.
thanks for the screenshot.

**Comment by leonsoft-kras** [comment]
Please try this version. After running in the file transgui.ini appears section:
[NetWork]
HttpTimeout=30
ConnectTimeout=60

Values in seconds.
Report the results.

[transgui.zip](https://github.com/leonsoft-kras/transmisson-remote-gui/files/1375564/transgui.zip)

**Comment by rd1** [comment]
it works, though i had to set http to 60 for the file move of 1,73GB to finish from local hdd to nas (qnap, arm 25MB/s write speed) 
  and it didn't throw a timeout error. 
  Though i do have bigger files, i'll probably have to set the http timeout to 10minutes to be safe.
  thanks
  
  
  
   ---------- Message d origine ----------
   De : Alexander <notifications@github.com>
   Daté : 11 octobre 2017 à 08:39
   
   
   Please try this version. After running in the file transgui.ini appears section: [NetWork] HttpTimeout=30 ConnectTimeout=60
   Values in seconds. Report the results.
   transgui.zip

**Comment by PeterDaveHello** [comment]
Preparing new release right now. Let's close this one as it's done in d19d9b4258552ba580497eb0acca445b1320f215

**Comment by PeterDaveHello** [comment]
https://github.com/leonsoft-kras/transmisson-remote-gui/releases/tag/v5.11.0
