### ISSUE TITLE
EXE filesize difference

### ISSUE THREAD

**Issue by wokuda** [leonsoft-kras/transmisson-remote-gui#1008]
Hello! Thank you for making such wonderful GUI :)

I have a question about the Windows version.

Portable version, transgui.exe = 904 KB
Installed version, transgui.exe = 2.77 MB

This is difference by 3 times the filesize. So I just want to know if there is a reason for it? Is there features missing on the Portable version and that's why it's lower by 3 times size?

Thank you.

**Comment by leonsoft-kras** [comment]
Hello! thanks!

In the portable version, transgui.exe is compressed with UPX v13_m8. 
There are no other differences. 
Why I did it I don't know. )))

**Comment by PeterDaveHello** [comment]
It's done by me, as zip tarball can't provide good enough compression ratio, I use UPX to compress it.
For the installation version, the installer will compress the binary, using UPX will only make the installer larger, that's why I didn't do it on the installer.

**Comment by hobo-mts** [comment]
But [UPX doc](https://github.com/upx/upx/blob/master/doc/upx.pod#notes-for-win32pe) says:

> Because of the way UPX (and other packers for this format) works, you can see increased memory usage of your compressed files because the whole program is loaded into memory at startup.

May be no reason to economize a few bytes?

**Comment by hobo-mts** [comment]
> Will UPX cleanup itself after that startup?

Yes. It finished OK.

> Do you have comparison of the memory usage of the compressed and decompressed version?

transgui.exe (compr) 14 724 KB
transgui.exe (decompr) 13 964 KB

Both run'n about 1 min.

**Comment by PeterDaveHello** [comment]
@hobo-mts if it'll clean itself up, seems no problem.

Thanks for the tests, look not very different, I'll find a windows to test, too.
