### ISSUE TITLE
Incompatible with MacOS High Sierra

### ISSUE THREAD

**Issue by srscott** [leonsoft-kras/transmisson-remote-gui#1011]
Unable to launch Trans GUI on High Sierra.
Please see attached images for errors.
![screen shot 2017-09-28 at 8 15 32 pm](https://user-images.githubusercontent.com/17326832/30962672-d22e4a84-a489-11e7-885f-6b82fea7834a.png)

![screen shot 2017-09-28 at 8 12 33 pm](https://user-images.githubusercontent.com/17326832/30962622-a835ac72-a489-11e7-8b7c-391bd47da034.png)

![screen shot 2017-09-28 at 8 16 14 pm](https://user-images.githubusercontent.com/17326832/30962692-eac0def4-a489-11e7-9bc0-d528afe7061b.png)

**Comment by chocochrispi** [comment]
same here

**Comment by leonsoft-kras** [comment]
We need to build the project directly on the makos (install FPC and Lazarus). So we blame who is to blame. This is a compilation program for all platforms or a problem in another.

In general, it is surprising that the development of the operating system leads to such failures. I did not see anything similar for such simple programs in Windows.

**Comment by junghoocho** [comment]
After encountering the same issue after High Sierra upgrade, Iinstalled version 5.10.0 downloaded here. 5.10.0 does not have the described issue on three Macs (two iMac and one MacBook Pro) that I have tried so far. It seems that the problem was with version 5.0.1 downloaded from sourceforge (which is unfortunately the first hit on google).

**Comment by PeterDaveHello** [comment]
@chocochrispi @srscott what's your transgui version?

I got no problem with v5.10 here. In #1006, looks like @rrolandd got no problem.

I can not compile a new macOS release right now, there are some behaviors changed in High Sierra and we need to update the scripts.

**Comment by chocochrispi** [comment]
@PeterDaveHello Transmission Remote GUI 5.0.1

**Comment by chocochrispi** [comment]
@PeterDaveHello all good with 5.10
Sorry to bother

**Comment by denmaus** [comment]
I got no problem with version 5.10.0 on High Sierra (but 5.0.1 don't work).
@srscott @chocochrispi  Grab the latest release from [https://github.com/leonsoft-kras/transmisson-remote-gui/releases](https://github.com/leonsoft-kras/transmisson-remote-gui/releases)

**Comment by PeterDaveHello** [comment]
Thanks for the updates.

**Comment by srscott** [comment]
Thanks for the update. Issue resolved with 5.10
