### ISSUE TITLE
Link to installers in README.md

### ISSUE THREAD

**Issue by mikaeldui** [leonsoft-kras/transmisson-remote-gui#1017]
I couln't find any link to the installers in the README.mb. That'd be nice to have.

**Comment by PeterDaveHello** [comment]
It's clear that our installers are located in the [releases](https://github.com/leonsoft-kras/transmisson-remote-gui/releases) page, isn't it?

**Comment by mikaeldui** [comment]
No it really isn't. I almost gave up on trying to find a download link.

**Comment by PeterDaveHello** [comment]
See if @leonsoft-kras has any idea.

**Comment by leonsoft-kras** [comment]
See the program website. 
We can make similar links in the readme-file.

http://leonsoft-kras.github.io/transmisson-remote-gui/
