### ISSUE TITLE
New in Git: Question about ignore file

### ISSUE THREAD

**Issue by antekgla** [leonsoft-kras/transmisson-remote-gui#1019]
Hi, I contribute to transgui in the past and @leonsoft-kras was nice enough to give me write permisions to the code.
I am very new to github and after a little search I find what the easy way to use is with Github Desktop.
I installed and clone this repository.

My question is: **why the folder /units is not added to the ignore file?**
When I open with Lazarus the file transgui.lpi and compile the project Lazarus create in that folder (units/) the transgui.exe and all the units compiled, besides transgui.exe create a new folder named home with the transgui.ini in there. I think what nothing in this folder is useful to the repository.

I am doing something wrong?
Thanks in advance!

**Comment by leonsoft-kras** [comment]
I did not understand the question.
The units, units/home folder is created when the project is compiled.
This folder does not fall into the repository. 
How she was there? Maybe show screenshots?

**Comment by antekgla** [comment]
Hi!,
I only open the project, **no changes**, compile, run and this is showed by Github Desktop:

![changes in units folder](https://user-images.githubusercontent.com/24402722/31771501-bcb7be72-b4b2-11e7-8a19-ec5a7fc01654.jpg)

The other 76 files in the units folders are filter by the **# Lazarus compiler-generated binaries (safe to delete)** part of the ignore file.

You say what when I **commit to master** this files are not uploaded?

**Comment by leonsoft-kras** [comment]
I probably will not tell you. I use the explorer/totel commander + TortoiseSVN.
I don't know what Github Desktop shows ))

**Comment by Diskutant** [comment]
The .gitignore file is missing a line containing 

`unit/`

If Github Desktop shows a change in a file it's a file that will be uploaded.

**Comment by antekgla** [comment]
I added the unit folder to the .gitignore file.
