### ISSUE TITLE
Ability to add new torrents in a stopped state

### ISSUE THREAD

**Issue by reedy** [leonsoft-kras/transmisson-remote-gui#1022]
It'd be really useful if I could add new torrents in a "stopped" state. Sometimes I want to bulk add tens of torrent files at once, but don't want them all to be active for varying reasons.

There is the "Start Torrent" option on the download options form, but you have to uncheck it for every individual torrent which gets annoying

Thanks!

**Comment by leonsoft-kras** [comment]
Is it suggested to remember the status of this flag? (not to take off every time)

**Comment by reedy** [comment]
That would be one way. Or have a flag/setting under Application Options in Add torrent where there is the option for "Prompt for download options...". This is how the rpc web interface of Transmission deals with it

<img width="370" alt="screen shot 2017-11-03 at 19 20 48" src="https://user-images.githubusercontent.com/67615/32392150-48c6f6c4-c0cc-11e7-9b83-a4861b543abb.png">

**Comment by antekgla** [comment]
Done!
Now the checkbox state is saved in transgui.ini

If you want to add several torrents in stop state without any options screen.

1. Add a torrent and uncheck Start Torrent.
2. Go to Application Options and uncheck **"Promp for download options when adding a torrent"**
3. From now all your torrent would be added in stopped mode in default folder.

**Comment by reedy** [comment]
👍

**Comment by antekgla** [comment]
@leonsoft-kras  please delete my two last commits because I dont know why I screw something with the last two @PeterDaveHello commits. I try to revert but no luck..
The commits to delete are: 
https://github.com/leonsoft-kras/transmisson-remote-gui/commit/9385e1b207048935c6ed0e4c303e7b4ab5428536
https://github.com/leonsoft-kras/transmisson-remote-gui/commit/e1ed85bee0c75513bab7783091e0537ae3355619

**Comment by leonsoft-kras** [comment]
I returned the old version of the files. How could.

**Comment by PeterDaveHello** [comment]
I can rewrite the commit history back to normal if @antekgla @leonsoft-kras you want :)

**Comment by leonsoft-kras** [comment]
You can try it.

**Comment by antekgla** [comment]
Please do it!
Just make sure what my commit https://github.com/leonsoft-kras/transmisson-remote-gui/commit/8b6e97ddf73998d1cca608f46f9d8e1824b4b480  don't get lost.

Thanks!

**Comment by PeterDaveHello** [comment]
Should be done now 👍

**Comment by PeterDaveHello** [comment]
BTW, @antekgla you can use `--rebase` with `git pull` to update the local branch next time so there won't be a merge commit 😄

**Comment by antekgla** [comment]
I never use git before and now and using Github Desktop what is very easy GUI to git, but sadly very limited. I can't do the full set of git command only simple pull and push and commits.
For example now after you cleaned all and run Github Desktop and appears this

![github fetch](https://user-images.githubusercontent.com/24402722/32409328-74a308de-c188-11e7-9b73-6e0edbe2f951.jpg)
I have fear what if I press that button the **5** commits you and @leonsoft-kras make today syncronize with my local repository but also appears **4** differences to push (I dont do any changes) :flushed:

**Comment by PeterDaveHello** [comment]
Preparing new release right now. Let's close this one as it's done 8b6e97ddf73998d1cca608f46f9d8e1824b4b480.

**Comment by PeterDaveHello** [comment]
https://github.com/leonsoft-kras/transmisson-remote-gui/releases/tag/v5.11.0
