### ISSUE TITLE
"Open Containing Folder" context menu item from lower "file" panel open file rather than folder

### ISSUE THREAD

**Issue by kissglay** [leonsoft-kras/transmisson-remote-gui#1027]
"Open Containing Folder" context menu item from lower "file" panel passing full file path (including the FILE NAME) as parameter rather than folder, causing file manager like Total Commander to crash.
![snag- 2017-11-08_09 36 48](https://user-images.githubusercontent.com/529385/32527519-4ce11f46-c469-11e7-8424-8522acafe499.png)

**Comment by leonsoft-kras** [comment]
Show the settings in your transgui.ini file (total commander path and etc.)

**Comment by kissglay** [comment]
```
FileManagerDefault=C:\tools\TotalCmd\TOTALCMD64.EXE
FileManagerDefaultParam=/O /T /R=%s
```
and I tested it passing it to a batch file, and it shows the parameter is the full path rather than the folder containing the file.

**Comment by antekgla** [comment]
@kissglay I tested with the **exact same config** you posted and all works OK, no Total Commander crash.
I make you a video to show you my results;

[Video in Youtube - Total Commander in TransGUI](https://www.youtube.com/watch?v=PI_FBbqKUrY)

**Comment by leonsoft-kras** [comment]
We need more data - your operating system, 32/64, etc.
Whether it is possible to launch 32-bit version of TC ?

**Comment by kissglay** [comment]
Sorry, guys.
 It's a total command issue. The last total command 9.12 rc2 crashes when executing something like
`C:\tools\TotalCmd\TOTALCMD64.EXE /O /T /L=c:\folder\file`, which transmisson-remote-gui passes as an argument.
But it's ok when executing `C:\tools\TotalCmd\TOTALCMD64.EXE /O /T /L=c:\folder`.
The previous version of total command took care of this situation.

**Comment by kissglay** [comment]
Sorry, it's pretty weird. I can't reproduce this problem on my side now.
