### ISSUE TITLE
Rules to automatically suggest download directory  

### ISSUE THREAD

**Issue by GoogleCodeExporter** [leonsoft-kras/transmisson-remote-gui#500]
```
Id like to have some rules to suggest download directory
Today its possible to select download directory from a list
but I'd like to have a path proposed to me from a predefined list
maintained by rules.

I'm using automatic (http://kylek.is-a-geek.org:31337/Automatic/) to 
automatically download files and each rule has its own download directory for 
its torrents. I'd like something like that for the download directories for 
torrents added with transmisson-remote-gui
```

Original issue reported on code.google.com by `marijoed...@gmail.com` on 24 Dec 2011 at 7:37

**Comment by leonsoft-kras** [comment]
Please use Release 5.1.0

**Comment by LuckierDave** [comment]
I know this is a super old ticket, but I wanted to confirm intended functionality before I opened a new ticket or something. I don't know Pascal to be able to check the source code, but is the code intended to auto-directory _only_ on the basis of file extension? I've tried using `*partOfFileName*` without an extension as a rule, but it doesn't seem to have any effect when I add a new file with that same `partOfFileName`. Thanks!

**Comment by leonsoft-kras** [comment]
It is only searched for the file extension. Pascal is not my second language for a long time.
Until there was a need to search for a more complex mask.

If you find a ready-made code sample or an algorithm for processing a file mask, then this can be modified.
