### ISSUE TITLE
gnome/nautilus - open containing folder works correctly - but gives error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [leonsoft-kras/transmisson-remote-gui#759]
```

What steps will reproduce the problem?
1. Add a local path mapping to the torrent folder 
2. Control+Return on any torrent
3. It correctly opens the folder in nautilus but also gives an error box 
containing:

Unable to execute "/torrent/directory/location/".


Transmission Remote GUI Version 5.0.1
Arch Linux with
GNOME Shell 3.10.4
GNOME nautilus 3.10.1
```

Original issue reported on code.google.com by `lvl70...@gmail.com` on 28 Feb 2014 at 11:05

**Comment by DiWa51** [comment]
FYI @leonsoft-kras , this [change](https://github.com/leonsoft-kras/transmisson-remote-gui/commit/afe7aa9d12e5a802b500ffe9991bd00a538af25f) is fixing this issue. 
I've tested with version 5.4.0 on Linux Mint with "smb://" remote mapped path and it works fine.
You can close this issue.

**Comment by jpbaril** [comment]
I'm not able to open remote shares on Ubuntu 19.04.
I have: /volume3/downloads=smb://192.168.0.2/downloads
I get the "Unable to execute" error and Nautilus does not open either.
