### ISSUE TITLE
Enhancement: allow clearing of recent paths

### ISSUE THREAD

**Issue by GoogleCodeExporter** [leonsoft-kras/transmisson-remote-gui#760]
```
Add an option to clear the recently used paths shown when adding a new torrent. 
Currently there is no way to do this.
```

Original issue reported on code.google.com by `bakermst...@gmail.com` on 2 Mar 2014 at 8:25

**Comment by lukaville** [comment]
Same problem! Please, add ability to clearing recent paths (or maybe add case sensitivity to recent paths combo box)

**Comment by leonsoft-kras** [comment]
ok

**Comment by lukaville** [comment]
@leonsoft-kras, many thanks for fixing this issue. Джва года ждал фикс :)
I thought that this project was abandoned on Google Code, I used old version of transmission-remote-gui, without update checking feature. I am very glad that the project is going forward.

I have a small request: can you publish MacOS build of latest 5.6 version?

**Comment by leonsoft-kras** [comment]
I do not have this OS. Look it up
https://github.com/leonsoft-kras/transmisson-remote-gui/issues/938
