### ISSUE TITLE
Open and Open containing folder don't understand transmission option for directy for incomplete files

### ISSUE THREAD

**Issue by GoogleCodeExporter** [leonsoft-kras/transmisson-remote-gui#838]
```
What steps will reproduce the problem?
1. Set transmission option 'Directory for incomplete files'
2. Add new torrent with a different download directory (I use 
`transmission-remote --add $torrent -download-dir $dir` to do this
3. Before the torrent is finished downloading, try to open the containing 
folder.

What is the expected output? What do you see instead?

I expect the directory within the incomplete file directory to be opened since 
that is where the torrent data is currently located. _After_ the torrent has 
completed downloading and transmission has moved the data from the incomplete 
file directory to the specified download directory would I expect 
transmission-remote-gui to try to open that directory.

Instead I get the error: "Unable to execute /download/directory/".

What version of the product are you using? On what operating system?

5.01
```

Original issue reported on code.google.com by `jtrad...@gmail.com` on 12 Oct 2014 at 4:09

**Comment by rd1** [comment]
yes, often i want to check out some of the finished files in an unfinished download.

in the paths box when setting up a new connection , i type in the incoming folder path and the windows equivalent, hoping this will be possible.

please add this so we can better manage our downloads, maybe save some bandwitdh if its a bad torrent, etc

**Comment by leonsoft-kras** [comment]
Perhaps the problem is that you do not configure the appropriate directory in the program settings

**Comment by rd1** [comment]
i know how unc paths work, i know how to setup the trg.

here is my incoming temp folder as it is set in my connection window and the windows UNC equivalent as per the example in the connection window:

/share/HDA_DATA/Download/qtransmission/incomplete=\\192.168.1.50\Download\qtransmission\incomplete

this is right. but it does not work.

**Comment by leonsoft-kras** [comment]
I am not the author of this program. What I can - I correct, finish.
I just can not stingy 3 lines guess all the steps to achieve the bug results.
If you do not work - the others can work, and vice versa.

**Comment by rd1** [comment]
you're the one not making sense now
