### ISSUE TITLE
Feature Request: Add a column for 'download remaining'

### ISSUE THREAD

**Issue by Sushubh** [leonsoft-kras/transmisson-remote-gui#881]
Not sure if this is the proper place to post a feature request. I just wanted an option named download remaining that tells me how much of the download is remaining. Size to download shows the complete download size not (size to download - data already downloaded). I just recently switched from Vuze on my computer to Transmission on a Pi and this is one of the few things I miss. Cheers. And thanks for maintaining this project!

**Comment by leonsoft-kras** [comment]
It seems everything is already there. column ETA

**Comment by leonsoft-kras** [comment]
![vvvvv](https://cloud.githubusercontent.com/assets/11468577/13845050/05453ce4-ec70-11e5-85c9-ca8d1e4d3837.jpg)

**Comment by Sushubh** [comment]
I was hoping to get a download remaining in size. I am already using ETA. I am migrating from Vuze and I miss seeing a quick glance over how much data remains to be downloaded. ETA does not work for inactive downloads for example. Thanks.

**Comment by leonsoft-kras** [comment]
Roughly speaking, you want to know how many bytes still need to download?

**Comment by Sushubh** [comment]
Yup. Size to download shows the total size of the download. A remaining option would be useful that would show the remaining download in MB/GB/etc for a quick preview and also helps in sorting to prioritize the downloads! 

Right now if all the downloads are paused... I cannot easily see how much download is remaining for individual entries in the queue! 

Thanks for considering. 

![remote](https://cloud.githubusercontent.com/assets/310098/13845396/bbdb981e-ec65-11e5-8963-92ce927dd9bc.png)

**Comment by rzcat** [comment]
https://github.com/leonsoft-kras/transmisson-remote-gui/pull/898
done, review needed

**Comment by leonsoft-kras** [comment]
Thanks, you can check.

**Comment by Sushubh** [comment]
Just installed the latest update. Thanks for adding the size left column!
