### ISSUE TITLE
Feature Request: Show my public IP on the UI somewhere

### ISSUE THREAD

**Issue by Sushubh** [leonsoft-kras/transmisson-remote-gui#882]
Maybe in the status bar. Would be helpful on seeing if I am connected directly or through VPN. Thanks.

**Comment by leonsoft-kras** [comment]
I think it is hardly possible. I do not see the need.
Address of the device that is running himself transmission, commonly known.
There are many websites that show you - how they "see" your address.
I think such a function in the transmission is not, and can not be.
