### ISSUE TITLE
Error: "2/26/2016" is not a valid date format,

### ISSUE THREAD

**Issue by Sunii** [leonsoft-kras/transmisson-remote-gui#883]
When adding .torrent files using the remote gui or double clicking in explorer, the error presented is:

[Window Title]
Error
[Content]
"2/26/2016" is not a valid date format
[OK]

 Adding the torrent using the default webui in a browser gives no error and the torrent loads fine.
This is occurring with every torrent file i try (I tried 6 from different sources). Using the add torrent dialog in the GUI causes it to crash if multiple torrents are selected.

**Comment by Sunii** [comment]
Also happens when doing "set data location", same error and the set data location dialog does not appear.

**Comment by Sunii** [comment]
Solution: I exported the settings to a file and found the line:

LastDt0=2/26/2016

near the bottom in the config, I removed the portion "2/26/2016" and imported the config back into the program. problem is no longer present.

**Comment by Sunii** [comment]
I have found a way to solve my issue from re-occurring by resetting my windows date & time formats to the default, as I had changed how the date is displayed on the windows taskbar in the clock area. I suspect this program is using a less than optimal way of determining the date used for the folder history or whatever said variable in the config represents. Hopefully this problem can be fixed.

**Comment by StentMan** [comment]
I've been seeing a lot of this myself, both when adding torrents or when trying to set data location. Very annoying:
[Window Title]
Error

[Content]
"01-Jan-00" is not a valid date format

[OK]

I haven't tried the the workaround suggested by Sunii (I'm on Windows 7) because it would be too confusing to use that US format in Windows Explorer all day. It's not an option for me. Where I live we use the DD/MM/YYYY format (day first, month second).

Please fix this.

**Comment by leonsoft-kras** [comment]
just for information. in the program the author used functions:
http://www.freepascal.org/docs-html/rtl/sysutils/strtodate.html
http://www.freepascal.org/docs-html/rtl/sysutils/shortdateformat.html

**Comment by purldator** [comment]
Also having the exact same problem.  I have to go back to the default web gui due to it.  This remote gui refuses any new torrents.  Same error as discussed above, due to the same reason: non-default time format set in Windows (10).

**Comment by rd1** [comment]
yep, same here, jsut upgraded to v5.4 with date columns showing

when i 1st launch trg the date format for columns added and last active are in my locale yyyy-mm-dd, then after i do an action on a file (right-click , set location) they change to dd-mm-yyyy.

**Comment by leonsoft-kras** [comment]
Once again you get an error contained in the first post for version 5.4? program crash?

**Comment by rd1** [comment]
yes, once again. i though this error was fixed. 

no crash no error, just reporting what i see, date gets mixed up after action on file, the whole column display gets changed not just the chosen file's date. 

lucky it doesn't do harm, just display.

When you use a program everyday you want to make sure it becomes bug free and as usefull & the best it can be. its all anyone wants.
