### ISSUE TITLE
gui options button on toolbar

### ISSUE THREAD

**Issue by rd1** [leonsoft-kras/transmisson-remote-gui#886]
hi Leonsoft, can you please add a button to open the gui's options.

**Comment by rd1** [comment]
and a shortcut key to go with it.

i'd also like to regain the F5 to show/hide the bottom panel. i open and close this pannel a hundred times a day.

maybe a toolbar button too for touch screens ?

**Comment by leonsoft-kras** [comment]
Now 2 buttons for Options is in the toolbar. Why more?
F5 to show / hide - I try to add.

**Comment by rd1** [comment]
because the 2nd button is not what i need, its useless.

its a big empty toolbar, there's plenty of room
