### ISSUE TITLE
Disconnections/timeouts from server...

### ISSUE THREAD

**Issue by rd1** [leonsoft-kras/transmisson-remote-gui#890]
i get timeouts frequently while using the gui

Anyone else have that problem ?

**Comment by leonsoft-kras** [comment]
T-R GUI performs periodic polling for Transmission (a period in the program settings). 
If this operation takes a long time, the GUI interface accordingly hangs.
When Transmission busy downloading this especially evident.

**Comment by rd1** [comment]
i know this, but there are ways to optimise.

have you checked if the connection to the server gets closed after each polling?

if so, leave it open. this will save cpu cycles on the server. not all servers are xeon. mine is a simple Qnap ts-212 with an ARM v5 cpu. it's a low power cpu.

another idea would be to use multiple connections to the server, 1 for each part of the gui.

another optimisation could be... ok, 1st get the overall stats like the server name, version number, speeds, etc. just global stuff.

While in multithread (?) you get the torrent list for only the number of torrents you can actually display in the list. 

The stats will show the user the speeds up/down, server ip, etc while the quick fetching of only about  30 torrents will give the user what he sees on screen.

this happens in a split second. the 2nd split of the second you can fetch the rest of the torrents that aren't displayed. you don't need to fetch all of the torrents and their data, just start with those onscreen first. then when this is done get the rest discreetly in background.

i'm sure there are ways this can be optimized. not all hardware is the same.

**Comment by leonsoft-kras** [comment]
I also do not like much. Offer is good, but it would require to rewrite a program completely.
I know that such a multitasking, etc. But I do not have time to rewrite this program.
