### ISSUE TITLE
Issue when compiling in windows.

### ISSUE THREAD

**Issue by iZeus83** [leonsoft-kras/transmisson-remote-gui#892]
Hello, 

It seems there's a problem when compiling the binary under windows. So this "transgui.res" file doesn't exist, it is included in source files?

`C:\Users\eugenio\Downloads\transmisson-remote-gui-master>make
Using Lazarus dir: C:\Lazarus
C:/lazarus/fpc/2.6.4/bin/i386-win32/ppc386.exe -MObjFPC -dLCL -dLCLwin32 -O2 -g- -CX -XX -Xs -Fusynapse/source/lib -Fujson -FuC:\Lazarus/lcl/units/i386-win32 -FuC:\Lazarus/lcl/units/i386-win32/win32 -FuC:\Lazarus/components/lazutils/lib/i386-win32 -FE. -FUunits/i386-win32 -di386 transgui.lpr
Free Pascal Compiler version 2.6.4 [2015/10/03] for i386
Copyright (c) 1993-2014 by Florian Klaempfl and others
Target OS: Win32 for i386
Compiling transgui.lpr
transgui.lpr(50,1) Error: Can't open resource file "C:\Users\eugenio\Downloads\transmisson-remote-gui-master\transgui.res"
transgui.lpr(50,1) Fatal: There were 1 errors compiling module, stopping
Fatal: Compilation aborted
make: *** [transgui.exe] Error 1`

thanks.

**Comment by leonsoft-kras** [comment]
Try the "Run -> Clean up and build ..."
as I understand the Freepascal, the transgui.res file is created at compile time.

**Comment by iZeus83** [comment]
> Try the "Run -> Clean up and build ..."
as I understand the Freepascal, the transgui.res file is created at compile time.

You mean from IDE?, I compiled from command-line

**Comment by leonsoft-kras** [comment]
IDE

**Comment by iZeus83** [comment]
Well It seems the compilation was successful because I compiled from "main.pas". So now I try to find where's the executable. I'm using the default output :/
