### ISSUE TITLE
Feature request: Ability to copy a peer IP

### ISSUE THREAD

**Issue by Underground78** [leonsoft-kras/transmisson-remote-gui#893]
It would be interesting if Transmission Remote GUI offered the possibility to copy a peer IP when right clicking on it.

It's probably pretty straightforward to add this feature but unfortunately I know nothing about Pascal.

**Comment by Underground78** [comment]
Was this implemented or did you choose not to do it?

**Comment by leonsoft-kras** [comment]
Not to do. I'm afraid I do not have time for this.
The more I do not understand the meaning of copying the IP addresses.
