### ISSUE TITLE
Linux binaries

### ISSUE THREAD

**Issue by Snegohod** [leonsoft-kras/transmisson-remote-gui#895]
If anyone it is necessary I have builded binaries for Linux.

transgui-5.1.0-x86_64-linux.zip https://yadi.sk/d/Zq6JvlcsqNqBE
transgui-5.2.0-x86_64-linux.zip https://yadi.sk/d/rQNuuv0rqNqB8
transgui-5.2.0-master-x86_64-linux.zip https://yadi.sk/d/Epa4YwtnqNqBJ
transgui-5.3.0-master-x86_64-linux.zip https://yadi.sk/d/LgDc9uahqh7uM

**Comment by peaveyman** [comment]
Which linux system did you build these on? Do you have a guide on how to do it?

**Comment by HendelTBD** [comment]
I'm looking all over for 5.2.0 OS X binaries, if anyone could help with that (or a "for Dummies" version of how to compile the source myself).

**Comment by Snegohod** [comment]
> https://github.com/leonsoft-kras/transmisson-remote-gui/issues/895#issuecomment-202809114
Ubuntu 14.04 64 bit. Lazarus 1.6 and fpc 3.0

```
Build the program by yourself.
- Make sure you have working Lazarus and Free Pascal compiler installed.
  * Free Pascal Compiler 2.6.2 and Lazarus 1.0 is used to develop Transmission Remote GUI. You may use different versions of FPC and Lazarus at your own risk.
- Download the sources archive and extract it to some folder or perform svn checkout. 
- Open terminal/command line prompt and cd to the sources folder;
- Execute "make" command to build the application;
- Execute "make zipdist" command to create a release .zip archive in the "Release" sub-folder.
```

Version 5.1.0 build from GUI. Other from command line because GUI caused error.

**Comment by Snegohod** [comment]
> https://github.com/leonsoft-kras/transmisson-remote-gui/issues/895#issuecomment-203555998

I will try to build OS X binaries on Monday.

**Comment by peaveyman** [comment]
When I run make I get this error:

Compiling transgui.lpr
transgui.lpr(50,1) Error: Can't open resource file "/home/gary/Downloads/transmisson-remote-gui-5.3.0/transmisson-remote-gui-5.3.0/transgui.res"
transgui.lpr(50,1) Fatal: There were 1 errors compiling module, stopping
Fatal: Compilation aborted
Makefile:1932: recipe for target 'transgui' failed
make: *** [transgui] Error 1

If I run the Lazarus GUI it complains about files that need to be deleted.

**Comment by peaveyman** [comment]
If you could build the binaries for linux for the new release I would be grateful.

**Comment by Snegohod** [comment]
> If you could build the binaries for linux for the new release I would be grateful.

I do it on Monday and will add here

**Comment by Snegohod** [comment]
> When I run make I get this error:
> 
> Compiling transgui.lpr
> transgui.lpr(50,1) Error: Can't open resource file "/home/gary/Downloads/transmisson-> > > remote-gui-5.3.0/transmisson-remote-gui-5.3.0/transgui.res"
> transgui.lpr(50,1) Fatal: There were 1 errors compiling module, stopping
> Fatal: Compilation aborted
> Makefile:1932: recipe for target 'transgui' failed
> make: *** [transgui] Error 1
> 
> If I run the Lazarus GUI it complains about files that need to be deleted.

Try to do
```
*Building from Lazarus IDE*
  * Run Lazarus IDE;
  * You need to install the package with transgui custom components before opening the transgui project. The package installation is needed only once. To install the package do the following:
    ** Select {{{"Package > Open package file (.lpk)..."}}} from the main menu.
    ** Locate the {{{trcomp.lpk}}} file in the program's sources folder and open it.
    ** Press the {{{Install}}} button in the package window.
    ** You will be asked to rebuild Lazarus. Do it to finish the package installation.
  * Open {{{transgui.lpi}}} project and build it.
```

**Comment by Snegohod** [comment]
[OS X binaries version 5.3.0](https://yadi.sk/d/gk4o_tVAqgxGz)

**Comment by Snegohod** [comment]
Add linux binary to version 5.3.0

**Comment by HendelTBD** [comment]
Thank you!

**Comment by Snegohod** [comment]
Add linux binary to version 5.4.0

**Comment by peaveyman** [comment]
Can you please build the version 5.5.0 binary?

**Comment by HendelTBD** [comment]
Please. 😃
