### ISSUE TITLE
Building the binary

### ISSUE THREAD

**Issue by peaveyman** [leonsoft-kras/transmisson-remote-gui#899]
I'm trying to build the binary on my computer. Ran make in the correct folder but it fails with this:

transgui.lpr(50,1) Error: Can't open resource file "/home/gary/transmisson-remote-gui.git/trunk/transgui.res"
transgui.lpr(50,1) Fatal: There were 1 errors compiling module, stopping
Fatal: Compilation aborted
Makefile:1932: recipe for target 'transgui' failed
make: **\* [transgui] Error 1

**Comment by leonsoft-kras** [comment]
I chose the menu "**Run - Clean up and build...**" (in Lazarus). All settings left at default.
Try. I did not do any special corrections in the project (I am not the author)

Please write the result

**Comment by peaveyman** [comment]
I can't get it to build for some reason. It keeps complaining about can't delete some files.

**Comment by rd1** [comment]
@peaveyman why not use the already built installer ?
