### ISSUE TITLE
customizable toolbar

### ISSUE THREAD

**Issue by rd1** [leonsoft-kras/transmisson-remote-gui#903]
An idea came to me, why not make a customizable toolbar like on windows explorer back in windows xp ?

we could right-click on the toolbar and customize to our liking, something like this window :

![404532 image0 1](https://cloud.githubusercontent.com/assets/1567489/14370175/5bcae6e2-fcf9-11e5-99a4-14dfc57c2bf3.jpg)

with everything from the torrent and view, tools menu, we can then choose exactly the toolbar we want. and a checkbox to use bigger buttons.

i would ideally put a button for "show/hide" bottom info panel, i open and close that thing a hundred times a day.

**Comment by rd1** [comment]
hi there, you know, there are other menu items we could add to the toolbar, like properties for selected files, that's one i use often.

and open folder too.

those would be nice to have.

**Comment by leonsoft-kras** [comment]
I don't think this is a super needed function. 99% of users add torrent to the program and check the download.

If other people have time to develop this functionality - I'll add their code to this version of the program.

**Comment by rd1** [comment]
i don't think we're in a situation with this code where things need to be "super needed" to get done.

the hard work was done long ago. now we are at a stage where easy things can be added and tweaked.
