### ISSUE TITLE
SSL/TSL Support is not compiled error

### ISSUE THREAD

**Issue by rd1** [leonsoft-kras/transmisson-remote-gui#904]
when checking for updates either automatically or through the help menu i get this error

![ssl-tslnotsupported](https://cloud.githubusercontent.com/assets/1567489/14507744/2bdad54e-0192-11e6-9685-ebb1fe1c59b3.PNG)

**Comment by DiWa51** [comment]
Same thing for me.
Does the app still support this feature with github? If not, then you'd better deactivate it.
Cheers

**Comment by leonsoft-kras** [comment]
try v.5.5.1

OpenSSL libraries are included in the distribution. You get this error because library has not been found on your computer.

**Comment by DiWa51** [comment]
Works on Linux with libressl-dev installed.
Thanks
