### ISSUE TITLE
Path mapping

### ISSUE THREAD

**Issue by peaveyman** [leonsoft-kras/transmisson-remote-gui#908]
Can someone explain how to use the path mapping in the options? I'm running Manjaro Linux, a spin off from Arch. Nothing I put in there seems to make a difference. I'm running the daemon on the same box that I'm running Transgui on if it matters.

**Comment by moonman** [comment]
If you are running on the same box then both sides should be the same i.e.
/media/files=/media/files

**Comment by bluehangel** [comment]
Hi,
Same question, couldn't setup the right path mapping.
The network path to the download folder is "\\FREEBOX\Akasa\Download"

Thanks
