### ISSUE TITLE
UI Lag when server is working hard on a fast download

### ISSUE THREAD

**Issue by cloneman** [leonsoft-kras/transmisson-remote-gui#912]
The UI lags when the server is working hard. I realize this is a server side bottleneck. However, in the case of transmission daemon, it creates UX lag.

I have a server capable of downloading at 30 MB/s (about 300mbit). However, I throttle it to 10MB/s because otherwise transmission-remote-gui interface lags a lot (spinning in top right corner, and takes 5-10 seconds to open up a menu).

I understand that the delays are bring introduced by the server, however the plain old web-ui doesn't "feel" as slow as transmission-remote-gui, even when the server is under fast-download stress. Perhaps the UI's interaction with the server can be decoupled from waiting for server data for a more smooth experience. I don't know to what extent this is a possible, but food for thought on an enhancement.

Thanks!

**Comment by leonsoft-kras** [comment]
I am aware of this problem. Because it was designed by the author of the program.
It requires a lot of effort and time to rewrite the program seriously. I do not have time for this.


I put the program on pause.
Perform the required actions with the torrents, and then rented to a pause.

thanks!
