### ISSUE TITLE
Download path is not absolute, again

### ISSUE THREAD

**Issue by xnoreq** [leonsoft-kras/transmisson-remote-gui#914]
Transgui 5.4.0
Transmission 2.92
settings.json contains:  "download-dir": ".."

Adding a torrent with transmission-remote <magnet> works, adding the same magnet with transgui results in this error:
"download directory path is not absolute"

Btw, why don't you update the sourceforge project? It still hosts 5.0.1.

**Comment by leonsoft-kras** [comment]
I'll see.

I have no relation to the author. I don't know who shared version 5.01 on sourceforge. Perhaps the author himself. I'm a spin-off from the project. I add some functionality and removes the errors.

**Comment by xnoreq** [comment]
I see. Btw, it's transmiss_i_on not transmisson.

**Comment by cfpp2p** [comment]
> settings.json contains: "download-dir": ".."
> 
> Adding a torrent with transmission-remote works, adding the same magnet with transgui results in this error:
> "download directory path is not absolute"

https://github.com/transmission/transmission/issues/173
