### ISSUE TITLE
French typo display error - torrent name

### ISSUE THREAD

**Issue by bluehangel** [leonsoft-kras/transmisson-remote-gui#916]
Specific french typo are not correctly displayed in the torrent list name.
Got "?" instead of all character with accent (ie "é", "è",...)

**Comment by leonsoft-kras** [comment]
Check that shows the web-interface for your torrent file.
Send your torrent file, if possible (a public example, without your accounts).

**Comment by bluehangel** [comment]
web-interface and transmission 5.1 from sourceforge is ok regarding this item.

**Comment by bluehangel** [comment]
One more exemple, link to torrent software used this time. Maybe en encoding typo support issue.
![916 img torrent - 2](https://cloud.githubusercontent.com/assets/279057/18416373/39589402-7813-11e6-956c-a5dde7d9a8a2.jpg)

**Comment by bluehangel** [comment]
Hi,

did you find something relevant on this issue ?

**Comment by leonsoft-kras** [comment]
Hi, 
I have not sought, I was busy.

First, I must find the torrent file from the "French files." I have no problem with the Russian torrent files.

**Comment by bluehangel** [comment]
yes, or in the pair list=> **µ**torrent

**Comment by leonsoft-kras** [comment]
The site T411.ch impossible to register and download the torrent. There are other options?

**Comment by bluehangel** [comment]
No other option at this time, 

Didi  you check that it was the right website, and not a fake ?
[www.t411.ch](url)
torrent: [](http://www.t411.ch/torrents/Heartland-Saison-2-Ep-1-9-VF-DVDrip)

**Comment by leonsoft-kras** [comment]
supposedly from my address has already been registered. it's impossible.
without registration is not possible to download the torrent. the site is not a fake.

Send a torrent file, if possible.
hkrjhdisahww@mail.ru

**Comment by bluehangel** [comment]
private tracker, I can't share torrent file.

Maybe you can recover your account

**Comment by leonsoft-kras** [comment]
Hi!
I checked the current version of the TR GUI 5.4.0, transmission 2.84 (14307). 
I found a torrent in French, uploaded through magnet links.  All symbols of language displayed without distortion.
![1](https://cloud.githubusercontent.com/assets/11468577/18996581/0c32c4dc-875b-11e6-9b5f-3b5ab7483a70.png)
![2](https://cloud.githubusercontent.com/assets/11468577/18996589/11ebef52-875b-11e6-9707-9d63bd890a2a.png)

**Comment by bluehangel** [comment]
Ok, thanks for your analysis.

Server side is Transmission 2.8, I will check update log of transmission and maybe open a ticket to update it on the server provided.
On other side, I don't know if this can be link to my computer ? I don't think but not sure...

**Comment by leonsoft-kras** [comment]
My version of OS have windows 7 sp1 x64.

Try to open the torrent:
https://yadi.sk/d/bqjhwGBavyFKm
https://yadi.sk/d/44lB7r-wvyFKo

**Comment by leonsoft-kras** [comment]
Try to open the following files with the French accented characters:
http://zetorrento.fr/torrents/all/236/comedie
http://torrentking.eu/movie-1964/fantomas-torrents/#

**Comment by bluehangel** [comment]
I got this yesterday:
![916 img torrent _error](https://cloud.githubusercontent.com/assets/279057/19012556/bbb3ddac-87b9-11e6-9192-85810138e0a8.jpg)

**Comment by bluehangel** [comment]
TR GUI 5.0.1 is Ok, no issue

Can you provide link to archives ? 5.3 ?

**Comment by leonsoft-kras** [comment]
https://github.com/leonsoft-kras/transmisson-remote-gui/releases/tag/v5.3.0

**Comment by bluehangel** [comment]
from sourcerforge TR GUI 5.0.1 is OK, no issue


from https://github.com/leonsoft-kras/transmisson-remote-gui/releases 

5.4.0: NOK
![916 img torrent](https://cloud.githubusercontent.com/assets/279057/19012666/b3a1595c-87bc-11e6-81fb-3823d7c7bd1f.jpg)

5.3.0: NOK

5.2.0: NOK ( but something different)
![916 img torrent - 5 2 0](https://cloud.githubusercontent.com/assets/279057/19012659/861310de-87bc-11e6-883d-d21daca8f142.jpg)

5.1.0: OK
![916 img torrent - 5 1 0](https://cloud.githubusercontent.com/assets/279057/19012684/086061c2-87bd-11e6-8276-5b2777594cf4.jpg)

So we have to ckeck 5.2.0 updates, and after maybe 5.3.0

**Comment by leonsoft-kras** [comment]
TRG has been modified to compile Lazarus 1.4 and above.

**Comment by bluehangel** [comment]
so it's link to unicode/utf8 support update.
http://wiki.lazarus.freepascal.org/LCL_Unicode_Support

found this as exmple:
http://forum.lazarus.freepascal.org/index.php?topic=31640.0
```
I tried with AnsiToUtf8 and even without anything and the result is not the one expected.

With AnsiToUtf8 "é" becomes "?"
and without AnsiToUtf8, the same "é" becomes a black diamond with a white "?"
```
[http://forum.lazarus.freepascal.org/index.php/topic,31640.msg202947.html?PHPSESSID=vfqr58foubh1l9qam8eucqejj7#msg202947](url)

**Comment by leonsoft-kras** [comment]
Thanks.
This solution is simple, but does not fit the project. I probably need time to rework (too many compilation errors).

**Comment by bluehangel** [comment]
I understand, unicode support with previous Lazarus/FPC is not easy. 2.0 Lazarus have improved Unicode support using features of FPC 3.0+ but there will be side effect and rework tasks.

**Comment by leonsoft-kras** [comment]
I can't repeat your situation. I tested version 5.4 to win 8.1 x64 eng and win 7 x32 eng. 
The program works correctly. All characters are displayed correctly.
Write if there are proposals to simulate your situation.

**Comment by leonsoft-kras** [comment]
Try to install the latest version of the Transmission (eg locally on your computer). I want to determine the cause of the incorrect display of characters (perhaps a special configuration of your Windows or old version Transmission).

Below are links to download the version of Transmission (win32/64)  when it is available on the website transmissionbt.com
https://yadi.sk/d/PRFVgKyjwVvoH
https://yadi.sk/d/bGd5OJWGwVvoR

**Comment by bluehangel** [comment]
No issue with Transmission QT client 2.92, remote session.

**Comment by leonsoft-kras** [comment]
ok, thanks.
I will try to find and check out the old version of Transmission.

**Comment by leonsoft-kras** [comment]
Try version 5.5
The problem is resolved?

**Comment by bluehangel** [comment]
Not solved.

**Comment by leonsoft-kras** [comment]
https://yadi.sk/d/5-awufrL35KeFE
try this version

**Comment by bluehangel** [comment]
not fixed

**Comment by leonsoft-kras** [comment]
please try the two versions from the archive: https://yadi.sk/d/NSP6e6jM35XjvS

test2 - this recommendations: http://forum.lazarus.freepascal.org/index.php/topic,31640.msg202947.html?PHPSESSID=vfqr58foubh1l9qam8eucqejj7#msg202947
but I normally displayed test1.

I have any version of TRG display French characters properly, a russian and english version of windows. It is difficult to imitate your problem.

**Comment by leonsoft-kras** [comment]
continue...
1) please write version of your operating system (windows, 32/64, language).
2) and write as it displays the archive: https://yadi.sk/d/7cMay7qk35Y4e4

**Comment by bluehangel** [comment]
From https://yadi.sk/d/NSP6e6jM35XjvS :
Test 1 ok
Test 2 Nok

Win 10, 64, fr

**Comment by bluehangel** [comment]
Torrent from archive:
la v�rit� sur charlie.truefrench.dvdrip.xvid.rip.lanfeust40.avi
Fantomas trilogy (1964-1967) 720p multi HighCode-PHD

**Comment by leonsoft-kras** [comment]
Thank you! Happy New Year!
I will see the program (Win10 fr).

**Comment by leonsoft-kras** [comment]
I installed on a virtual machine Win10 Fr (x32), TRG 5.5.0 (yesterday's [release](https://github.com/leonsoft-kras/transmisson-remote-gui/releases/tag/v5.5.0) )
I uploaded 2 torrent. I do not see a problem. (((

![01](https://cloud.githubusercontent.com/assets/11468577/21580384/12e44eba-d024-11e6-9e20-55c782e66105.png)
![02](https://cloud.githubusercontent.com/assets/11468577/21580389/1c20a5aa-d024-11e6-8406-0ab44e1dc72f.png)
![03](https://cloud.githubusercontent.com/assets/11468577/21580388/1c1dbc5a-d024-11e6-8376-0049cc34f7c8.png)
![04](https://cloud.githubusercontent.com/assets/11468577/21580390/1c559634-d024-11e6-94c6-205394bc744b.png)

**Comment by bluehangel** [comment]
ok, thanks.

I will investiguate.
