### ISSUE TITLE
Italian Translation REV.14 by GNOGNi (2016-09-04)

### ISSUE THREAD

**Issue by gnogni** [leonsoft-kras/transmisson-remote-gui#917]
http://gnogni.altervista.org/updates/transgui_it_rev14_by_GNOGNi_2016-09-04.zip

A full italian translation of Transmission Remote GUI v5.4.0 with some improvements.
Have a nice day!

**Comment by leonsoft-kras** [comment]
thanks )))

**Comment by leonsoft-kras** [comment]
fix in v.5.5.0

**Comment by gnogni** [comment]
Many thanks! Happy 2017!!

**Comment by leonsoft-kras** [comment]
Thank you too! Happy New Year )))
