### ISSUE TITLE
Invalid floating point operation when adding torrent

### ISSUE THREAD

**Issue by Davikar** [leonsoft-kras/transmisson-remote-gui#920]
I have a big problem when using this program on Linux.
I add a torrent, pick where I want to save it and then when I click Ok I almost always get "Invalid floating point operation". The dialog keeps reappearing a couple of times, then I get "Access violation", but it still starts. Sometimes the Invalid floating point dialog just keeps reappearing and it makes it impossible to start the torrent. I can pick to save it somewhere else and then it _might_ work.
I'm running this on Manjaro with Gnome 3.20.2.

**Comment by leonsoft-kras** [comment]
There are cases when the error does not occur and the torrent download procedure is performed successfully?

**Comment by Davikar** [comment]
Yes, but they don't happen often. Usually if I don't have to change the download folder it seems I don't get the error, or if I pick a folder from the history.

**Comment by leonsoft-kras** [comment]
Thank you for this useful information for me. I'll think about it.
Write, if there are more details.

**Comment by peaveyman** [comment]
I have seen this problem also.

**Comment by DiWa51** [comment]
Hi,
I faced this issue too on 5.4.0 on Linux.
It worked well for the 1st torrent added, but then for subsequent ones this error is raised.

Though if I keep the default proposed path (coming from the last successful addition I guess) then the torrent is added without error. I then need to select this newly added torrent and set its data location to the correct path.

Hope this can help.

**Comment by peterLaurence** [comment]
I always get this error when i change the data location of a downloaded torrent. Though the data are successfully moved, this error is nagging.

**Comment by leonsoft-kras** [comment]
please try v.5.5.1
the problem is solved?

**Comment by DiWa51** [comment]
Hi,
Today's tests are successful for me on the Linux version!
Thanks for this

**Comment by Davikar** [comment]
Yes, this is working fine now!

**Comment by Davikar** [comment]
Looks like the problem might not have been entirely solved.
I'm getting a similar error message now when trying to add new torrents.
It tells me "download directory path is not absolute". I get the same error message where ever I try to save the file. This time there doesn't seem to be any workaround.
I have about 1200+ torrents loaded, not sure if that affects the problem.

**Comment by cfpp2p** [comment]
> ..."download directory path is not absolute"...

It's a problem with the official daemon and that bug is stuck in a conflict.
https://trac.transmissionbt.com/ticket/5825#comment:3
https://trac.transmissionbt.com/changeset/14594

**Comment by Davikar** [comment]
Ok, but I don't have this problem on the Windows version of TRGUI?

**Comment by cfpp2p** [comment]
> Ok, but I don't have this problem on the Windows version of TRGUI?

It's a twisted problem.

https://github.com/leonsoft-kras/transmisson-remote-gui/issues/891#issuecomment-210678045

https://github.com/leonsoft-kras/transmisson-remote-gui/issues/914#issuecomment-277918743

**Comment by leonsoft-kras** [comment]
1. Please write version:
- TRGUI
- OS
- transmission

2. You did not try to delete the file "transgui.ini" and reconfigure TRGUI before the download operation?
