### ISSUE TITLE
TLSv1.2 and modern ciphersuites support

### ISSUE THREAD

**Issue by kerio92** [leonsoft-kras/transmisson-remote-gui#922]
Hi, it would be appreciated if the TLS library could be updated, to allow connections to servers that mandate modern versions of TLS.

**Comment by gongzhenjeef** [comment]
I found this patch from sourceforge:
https://sourceforge.net/p/transgui/tickets/912/

**Comment by leonsoft-kras** [comment]
I changed 2 lines. Other long time already in the code.)))
Thanks

OpenSSLVersions: array[1..4] of string = 
('0.9.8', '1.0.0', '1.0.2', '1.1.0');

**Comment by leonsoft-kras** [comment]
Try version 5.5
I applied the patch, but not tested

**Comment by gongzhenjeef** [comment]
Seems still broken after I raised the limit from tls1.0 to tls1.1 with my built trouble? version for Mac. 
[transgui.zip](https://github.com/leonsoft-kras/transmisson-remote-gui/files/674431/transgui.zip)

**Comment by leonsoft-kras** [comment]
please try v.5.5.1

**Comment by kerio92** [comment]
Could we get a mac build for v5.5.1?

**Comment by Snegohod** [comment]
@kerio92 maybe later. Now I do not have a computer with OS X to build new version.

**Comment by gongzhenjeef** [comment]
@Snegohod The latest build for OS X works but still refuse tls1.1.
I found no significant changes with code related to ssl, but three additional dll for openssl for Windows is added. Maybe some dylib should be added? Not familiar about these.
@kerio92 Also tried windows version 5.5.1 on my XP VM, and it prompts "cannot load OpenSSL library: ssleay.dll and library.dll" though these files lies in the same directory with transgui.

**Comment by leonsoft-kras** [comment]
1. https://www.google.com/?gws_rd=ssl#newwindow=1&q=SSL%2FTLS+support+is+not+compiled!

2. I do not know why in the XM VM library is not loaded. I compiled a library of the latest source using Visual Studio 2008. On good it was necessary to install the system "Microsoft Visual C++ 2008 Redistributable Package (x86) .exe"

**Comment by gongzhenjeef** [comment]
Sorry, maybe I didn't express the issue clear. I install it on a fresh Windows XP virtual machine, and the application prompt that the library cannot be loaded. Then I tried to manually register the two DLL, still failed. Then I removed these two DLL and install a light version openssl library from the link to system32, then the application works. When I moved the original DLL back, the error appears again. Essential components in VC++ 2008 is included in msvcr90. As the DLL located in the application folder has high priority to load, so I thought the library shipped with installer may have compatible problems with old operating system. Then I checked both DLL, same version as 1.02j but from different builds.

**Comment by leonsoft-kras** [comment]
I understand about XP. OS probably did not have a manifest file in XP. It is not so simple. I think we shall understand in the next versions.

I do not know what the problem is in the OS X (tls1.1) and how to solve it.  A Mac computer is required, the time and desire. ))))

**Comment by Snegohod** [comment]
@gongzhenjeef try to install libssl-dev on OS X. In Linux it helps.

**Comment by leonsoft-kras** [comment]
total:
- Now **Windows version** installs **Microsoft Visual C++ 2008 Redistributable Packages**.
- **Mac and Linux** - it is necessary to install **libssl-dev**

**Comment by gongzhenjeef** [comment]
Still failed for OS X... Does anyone has an working build?
@Snegohod There is no such libssl-dev for OS X, I install openssl 1.0.2k with homebrew and it report protocol not support. Then I manual link OpenSSL file with SIP disabled, it report OpenSSL library not found.
