### ISSUE TITLE
Flags.zip download fails with HTTP 404

### ISSUE THREAD

**Issue by xnoreq** [leonsoft-kras/transmisson-remote-gui#923]
Flags.zip download fails with HTTP 404, because it tries to download from https://transmisson-remote-gui.googlecode.com/files/flags.zip, which doesn't exist anymore.

**Comment by jeancf** [comment]
Same here.

**Comment by rzcat** [comment]
Fix it manually:
0. close your exe
1. download flag icons from here http://www.famfamfam.com/lab/icons/flags/
2. unzip those *.png files into somewhere like "C:\Users\**USERNAME**\AppData\Local\Transmission Remote GUI\**flags**\" (Win8.1)
3. the "Transmission Remote GUI" dir should already be there if you've used it, while the "flags" dir does not exist if you've never managed to download flags.zip
4. if you're not sure about the path above, navigate your explorer to %appdata% and see where it goes
5. make sure the png path is something like ...\AppData\Local\Transmission Remote GUI\**flags\jp.png**
6. modify ...\AppData\Local\Transmission Remote GUI\transgui.ini, make **ShowCountryFlag=1** in  **[PeersList]** section
7. reopen exe, done
----
off-topic
if only theres a map plugin which shows the peer location on map...just like utorrent does

**Comment by leonsoft-kras** [comment]
I fixed the link in the program.
