### ISSUE TITLE
TransGUI 5.01 MOD (Shortcuts!, shortcuts!, shortcuts!)

### ISSUE THREAD

**Issue by antekgla** [leonsoft-kras/transmisson-remote-gui#924]
Hi, I want to share with you my MOD of TransGUI.
It is based in the last snapshot of the code (5.0.1) founded in Sourceforge by its original author and compiled with Lazarus 1.6 (FPC 3.0.0) in Windows 7 x64 . (Sorry! I only discover this 5.04 MOD later on)

My MOD **don't touch any of the functionality of 5.01 TransGUI**. My modifications are ALL about the Interface and mainly adding shortcuts and sometimes lets you define the shortcuts you want.
If you are preferes keyboard over mouse, this MOD is for you! 

Here is the complete list of my modifications:

-  **New ShortCuts**: _(sorry this are fixed shortcuts, they can't be changed)_
        **Alt + 1**  :  All Torrents
        **Alt + 2**  :  Downloading
        **Alt + 3**  :  Completed
        **Alt + 4**  :  Active
        **Alt + 5**  :  Inactive
        **Alt + 6**  :  Stopped
        **Alt + 7**  :  Error
        **Alt + S**  :  Searchbox (filter torrents by keywords) - **Esc** cancel filter and clean the box.
        **Alt + G**  :  Info Pane - General Tab
        **Alt + K**  :  Info Pane - Trackers Tab
        **Alt + P**  :  Info Pane - Peers Tab
        **Alt + F**  :  Info Pane - Files Tab

- Lets you define **ALL** menu's shortcuts
        This is done by a new section in transgui.ini **[Shortcuts]**. If you run this new exe without this new section in transgui.ini you will see what the all shortcuts are gone! Don't worry copy the [Shortcuts] section in /units/home/transgui.ini from the .zip file in your transgui.ini and you have again all the default shortcuts. Now you can change one or all of them at your own taste. 
You could see it looking at the transgui.ini attached, but the formula is: _MenuAction=Shortcut_  
Examples are:
AddLink=**Ctrl+Ins**
AddTorrent=**Ins**
AddTracker=
DaemonOptions=**F9**
Options=**Ctrl+F9**

- **System Wide Hotkey** _(Windows Only)_
      This new MOD allows you to define a System Wide Hotkey to activate TransGUI when the application is minimized in the tray. Unfortunately this new feature is Windows Only because every OS is very different at this and according to my limited knowledge it's not possible in linux. In MacOS I dont know but being so similar to linux probably will not be possible either.
   This new feature is acomplished by adding two new values in the **[Interface]** section of transgui.ini like this:
GlobalHotkey=**VK_T**
GlobalHotkeyMod=**MOD_ALT + MOD_CONTROL**
This makes **CTRL+ALT+T** (or **AltGr+T**) your System Wide Hotkey 
The vaues for _GlobalHotkey_ are named _VirtualKeyCodes_ and you have a full list [here](http://docwiki.embarcadero.com/RADStudio/Seattle/en/Virtual_Key_Codes) 
Not all codes could applies to your system, depends on your keyboard and regional settings. Try to find one what work for you.
The values for GlobalHotkeyMod are only 4: **MOD_SHIFT , MOD_CONTROL , MOD_ALT , MOD_WIN** . They could be used alone or combined with the sign + like the previous example. (MOD_ALT + MOD_CONTROL). This setting could be leaved blank if you don't want a combination of keys:
GlobalHotkeyMod=
For example if you want what **F9** would be your System Wide Hotkey assign **VK_F9** to GlobalHotkey and leave GlobalHotkeyMod blank.
The reason I chose this (more complicated) method unlike the previous one (assigning a simple String like **Alt+Ctrl+F9**) is because some keys are not possible to use with the earlier method. PAUSE is an example, if you assign the shortcut **PAUSE** to a menu this dont work, but you could assign the **VK_PAUSE** value to GlobalHotkey and **Pause** would be your System Wide Hotkey.
This Global Hotkey is a _toggle key_ meaning what if TransGUI is minimized the hotkey brings the Application at front but if the TransGUI is the active window the hotkey would minimize the Application.

- **Use another File Manager (not explorer.exe) to open folders.** _(Windows Only)_
Many people replace the Windows's default filemanager for another (more capable) program: Total Commander, Directory Opus, FreeCommander XE, Xplorer2, etc. This programs automatically replace all your aperations of opening files and folders (usually thru a registry modification to replace explorer as your default filemanager). When you choose _Open Containing Folder_ in TransGUI and the torrent has several files in his own folder this works OK, the folder are opened in the alternative program, but there is a case in TransGUI when you choose _Open Containing Folder_ and **the torrent only has one file and don't have his own folder** what it is open in explorer.exe instead because that is hardcoded in TransGUI code.
Now it is possible to handle this cases with the filemanager of your choice.
To do that you have to add 2 new values in the **[Interface]** section of your transgui.ini:
FileManagerDefault=**C:\Program Files (x86)\FreeCommanderXE-32\FreeCommander.exe**
FileManagerDefaultParam=**/C /T /L="%s"**
The first value _FileManagerDefault_ is the location of your filemanager executable. The second value _FileManagerDefaultParam_ are the parameter[s] what that filemanager needs and could be optionals but varies from one filemanager to another. In my case (**/C /T /L="%s"**) tells to FreeCommander XE to open the file in the current instance (if any) of FreeCommander, in the left pane and with that file selected.
Read the documentation of your filemanager to learn the parameter[s] your program needs (if any).

- **New Colum available in torrent list: Size Left**
This code is borrowed from Issue #881 
Thanks @rzcat and @leonsoft-kras 👍 

- **New information in Status Bar: Total Size, Selected Size, Done Size, Remain Size**
I added new data to the Status Bar based in the torrents (viewed or selected) in the torrent list. This display of additonal Info is user selectable, if you don't want this new data uncheck the Menu: _View-->Status Bar - Sizes_
![new data sizes short](https://cloud.githubusercontent.com/assets/24402722/20943823/cabb9baa-bbdf-11e6-8d8c-221800a791ef.jpg)
If one torrent is selected (torrent list always have at least one torrent selected) the data is about all torrents displayed. If more of one torrent are selected then the data correspond to this selection.
Data explained:
**Total**: Total size of torrents viewed/selected.
**Selected**: Sum of  the size of the files selected to download. For example if a torrent with 100 files is 50 GB in size but you marked 30 files totaling the sum of 15 GB to _Don't Download_ then this number reflects only the size of the files you actually want to download. (35 GB)
**Done**: Size of the data already downloaded of the torrents viewed/selected.
**Remaining**: Size of the data pending to download of the torrents viewed/selected.

You could download my MOD [here](http://s000.tinyupload.com/index.php?file_id=00835819961307792747)
The **transgui.exe** (Windows) is in the folder **\units**
The **transgui.ini** for copy and paste the new keys to your ini is in the folder **\units\home**

If you don't trust in exe's supplied by strangers in the Internet (**good for you!**) you could compile my MOD yourself . All the code is there.
As I say i compile it with **Lazarus 1.6 (FPC 3.0.0)** in **Windows 7 x64** 

@leonsoft-kras if you find some feature of my MOD interesting feel free to include them in your version. All my changes are in _main.pas_ and I add a new unit _StringToVK.pas_. Only you have to make a diff between the original code in SourceForge and my main.pas to view the differences. There are not so many! There is also a subtle modif in _main.lfm_
Cheers!

**Comment by leonsoft-kras** [comment]
thanks ))

**Comment by RougeTomate** [comment]
Great, thanks! I love shortcuts.
