### ISSUE TITLE
The entire project is an issue

### ISSUE THREAD

**Issue by qtwigg** [leonsoft-kras/transmisson-remote-gui#925]
I truly can not be the only. The last two years I have used this program not once has it worked right or did anything right. I can not click on anything with out getting bombarded with errors, or just freezes and becomes unresponsive. For example, I click one torrent to highlight it and boom, it freezes, give 4, 5 or 6 errors and I have to end process, I select anything, right click, double click, switch servers, press ctrl+r or f9, menu>add, switch view or sort by view, error after error and non stop error and it takes minutes upon minutes to add a single torrent because of all the errors and me having to end processes. This entire project needs to be pulled and wiped from the internet and the developer really needs to be placed against the wall. If you can not making something then do not waste our time.

**Comment by leonsoft-kras** [comment]
You do not like - go by and do not waste time scribbling.

I am not the author of the program. I modify the program for free, and when I have time for it. I use this program every day, and almost no problems.
