### ISSUE TITLE
Are you kidding me?

### ISSUE THREAD

**Issue by qtwigg** [leonsoft-kras/transmisson-remote-gui#926]
This does not work at all without excessive errors on everything you do and my now I see my issue was removed, seriously? What is the point of making an issue if it is going to be removed? Do not lie to me, you can not possibly be using this everyday without no problem. Not a single part of any of this program works, ever, no matter the version or OS or anything and I can prove this. I do anything and I get access violation errors, json error, no method name, ngix? errors after errors when even doing the simplest task like sorting by view or updating or adding or hell even clicking on one to view the peer status, error, error and more errors.
DO NOT REMOVE THIS POST!!

**Comment by eratnik** [comment]
I have everything working just fine. Always without errors. Windows 10 64-bit. Everything cool.
PS Что за чиканутый чел, аж противно... автор, не слушай его - софт просто крутой.

**Comment by Davikar** [comment]
Windows version works fine for me. I only have problems with the linux version. But I am running it under wine now and it works fine there.

**Comment by mrfearless** [comment]
Im using windows 7 x64 and running transmission 2.84 on my Qnap TS-453A and all seems fine. Previously i ran transmission server from a Qnap TS-219P which every now and them froze up for a few seconds as i changed something like download limits etc - depending on the amount of torrents downloading concurrently. Very rarely it crashed or crashes with my current setup, only noticed it once or twice freezing as i woke up computer from hibernation.

Sounds like it might be a server issue, as in the server isn't able to handle the request properly, which in turn causes the exceptions/crashes. 

Maybe if you have some info about your setup and the setup for your transmission other users might be able to suggest some steps to help narrow down the cause of the errors and/or suggest remedies/fixes.

**Comment by Diskutant** [comment]
I have those errors sometimes, but that happens only if Transmission (not the remote gui, but the actual Transmission on the NAS or whatever) is unresponsive. This happens when a big file is written, or other similar tasks.
