### ISSUE TITLE
Linux zip file for 5.5

### ISSUE THREAD

**Issue by peaveyman** [leonsoft-kras/transmisson-remote-gui#927]
Are you going to provide the linux zip file for the 5.5 release like you have for 5.4?

**Comment by leonsoft-kras** [comment]
I did not compile for Linux and Mac.
For previous versions compiled good people )))

**Comment by peaveyman** [comment]
So someone else compiled the binary for linux?

**Comment by peaveyman** [comment]
If whoever built the binary for linux on the last release could build it for 5.5 it would be greatly appreciated.

**Comment by RougeTomate** [comment]
5.5 dmg for Mac will be appreciated.

**Comment by Snegohod** [comment]
@peaveyman soon. When I will be at home.
@RougeTomate maybe later

**Comment by peaveyman** [comment]
Thanks!!!!

**Comment by leonsoft-kras** [comment]
try 5.5.1

SSL/TLS support fixed introduction of libraries in the windows-installer.
I do not know how this problem is solved in Linux or Mac. Probably similar.

I rewrote reading date from the file. I did not understand why there is an exception in functions StrToDate.

**Comment by Snegohod** [comment]
[Add linux binary 5.5.1](https://github.com/leonsoft-kras/transmisson-remote-gui/releases/tag/v5.5.1
)

**Comment by Zialus** [comment]
What about MacOS?

**Comment by Snegohod** [comment]
@Zialus maybe later. Now I do not have a computer with OS X.

**Comment by Snegohod** [comment]
@leonsoft-kras to solve the problem on linux install libssl-dev

**Comment by mpeterson** [comment]
@Snegohod hey, I would be grateful if you could also create instructions on how to compile it in OS X. I tried and no matter what I tried I received the following error:

`Linking ./transgui
ld: library not found for -liconv
An error occurred while linking
transgui.lpr(50,1) Error: Error while linking
transgui.lpr(50,1) Fatal: There were 1 errors compiling module, stopping`

**Comment by Snegohod** [comment]
@RougeTomate @Zialus @mpeterson make [OS X application](https://github.com/leonsoft-kras/transmisson-remote-gui/releases/tag/v5.5.1) manually. Test please

**Comment by Zialus** [comment]
@Snegohod It seems to be working. Thanks 😄

**Comment by RougeTomate** [comment]
Working fine for me, thank you!

**Comment by mpeterson** [comment]
@Snegohod it works, but how did you get past the linking error? care to share? Thanks

**Comment by Snegohod** [comment]
@mpeterson compiled in Lazarus GUI and created manually application.
Script to make OS X build is not working for the new versions. It is necessary to rewrite the script. May be I'll rewrite later.

**Comment by leonsoft-kras** [comment]
can be in addition adjusted this page?
http://leonsoft-kras.github.io/transmisson-remote-gui/

**Comment by RougeTomate** [comment]
Latest release is 5.5.1 but computer is showing I have 5.5.2. I guess I updated within the app, and am curious why it is not on the release page.

**Comment by leonsoft-kras** [comment]
it means the source files were not from the archive: 
https://github.com/leonsoft-kras/transmisson-remote-gui/archive/v5.5.1.zip
In the current version of svn 5.5.2 has new changes.

**Comment by Snegohod** [comment]
@RougeTomate I compiled from latest version with all changes not from source 5.5.1

**Comment by peaveyman** [comment]
Snegohod: Many thanks for your work in the past. Will you be building the binaries for the new 5.6 release?

**Comment by Snegohod** [comment]
@peaveyman Of course, but later.

**Comment by Snegohod** [comment]
@peaveyman add binary of [5.6](https://github.com/leonsoft-kras/transmisson-remote-gui/releases/download/v5.6.0/transgui-5.6-x86_64-linux.zip)

**Comment by Zialus** [comment]
Any chance of a macOS binary?

**Comment by Snegohod** [comment]
@Zialus soon
