### ISSUE TITLE
Error: LS-007. Please contact the developer

### ISSUE THREAD

**Issue by CarlosVelasco** [leonsoft-kras/transmisson-remote-gui#928]
Using new version 5.5.0
Whenever I use "Add Torrent Link" and submit a link, a window is opened showing "Error: LS-007. Please contact the developer".
Error is unrecoverable. Window can not be dismissed.

Platform: Windows 10 64 bits
Transmission: 2.92

**Comment by leonsoft-kras** [comment]
1. Make export settings (save transgui.ini)
2. Locate the file transgui.ini section "[AddTorrent."
3. Locate "LastDt" keys
4. Write here all values LastDt. I'll see that you are now in the ini-file.
5. Remove all keys "LastDt" from the file. Save ini-file.
6. Import the settings in the program.
7. Restart the program.

**Comment by ScottESanDiego** [comment]
I had the same issue, but only had:

LastDt1=01.01.2000
LastDt2=

**Comment by k0ste** [comment]
Also have this issue.
Helps to delete all history sections.

**Comment by leonsoft-kras** [comment]
Some users have been incomprehensible failures. I put the check. I expected to see the date in the format 2016.02.20 or 02.20.2016. So I'm not understand why there is a failure in reading the date in the correct format dd.mm.yyyy.

**Comment by Davikar** [comment]
I remove the entries, but TRGUI just keeps re-adding them...

**Comment by cfpp2p** [comment]
On windows at one point I was receiving exception boxes two times each torrent add
"**Error: LS-007. Please contact the developer**"

`main.pas` line 6608

```
    except
   	MessageDlg('Error: LS-007. Please contact the developer', mtError, [mbOK], 0);
        pFD.Lst := EncodeDate(2000,1,1); // last time folder
    end;
```

but then I

Tools --> Transmission options...
and reset '_Default download folder on remote host_'
and this stopped. Now I can't seem to repeat this even with a
non existent or invalid folder, no matter what.
