### ISSUE TITLE
Edit tracker = Error

### ISSUE THREAD

**Issue by Finch29** [leonsoft-kras/transmisson-remote-gui#929]
hi i have this error when i want edit the tracker ... : 

https://i.imgur.com/a2IgHDQ.png

**Comment by Snegohod** [comment]
me too.
In version 5.4.0 everything ok.

**Comment by antekgla** [comment]
I think what the function UTF8Decode in line 6750 is making this error.
I replace **UTF8Decode** with **UTF8Encode**  in **MainForm.Addtracker**
````Pascal
        if EditMode then
          args.Add('trackerReplace', TJSONArray.Create([id, UTF8Decode(edTracker.Text)])) //UTF8Decode
        else
          args.Add('trackerAdd', TJSONArray.Create([UTF8Decode(edTracker.Text)])); //UTF8Decode
````

with this:
````Pascal
        if EditMode then
          args.Add('trackerReplace', TJSONArray.Create([id, UTF8Encode(edTracker.Text)])) //UTF8Decode
        else
          args.Add('trackerAdd', TJSONArray.Create([UTF8Encode(edTracker.Text)])); //UTF8Decode
````
...tested and works.

I have absolute no idea why UTF8Decode/UTF8Encode was inserted all over the code.
I know what convert between Unicode <--> RawString but I dont know why this was added now.
Maybe @leonsoft-kras could clarify is use.

Cheers

**Comment by leonsoft-kras** [comment]
Russian characters are no longer displayed in the program during the transition from Lazarus 1.2.6 to 1.4.
I removed all the transformations (decode, encode). Programm build and work right for me.
When there was Lazarus 1.6.2, I tried to go back to the source code 5.0.1 (conversion function).  Some user had problems with torrents display.
I'm somewhere made a mistake when returning conversion function.

I think we'll fix some comments and suggestions, and then we'll do another version of the program.

**Comment by leonsoft-kras** [comment]
If the function is working, it means that the error was in the original version.
I compared the sources. ))
![11111](https://cloud.githubusercontent.com/assets/11468577/21631324/7855e700-d26c-11e6-9c67-918eb4b7f0ab.png)

In the author's program uses string, widestring and etc. I decided to return to the original state to avoid unexplained problems in the program.

**Comment by antekgla** [comment]
Yes, it is strange.
The function are in the code of 5.0.1.
I compiled that version but if you edit a torrent not fires a error. 😮

**Comment by leonsoft-kras** [comment]
I have corrected the code as you suggested. We should be tested.

**Comment by antekgla** [comment]
I tested with 5.5.1 changing UTF8Decode to UTF8Encode and works.
Buy I wonder why in 5.0.1 the UTF8Decode function works OK...
I keep working in this...
