### ISSUE TITLE
Windows client freezes if torrent files have illegal characters

### ISSUE THREAD

**Issue by tuluse** [leonsoft-kras/transmisson-remote-gui#933]
I run transmission as a daemon on a Linux server, and connect from Windows. I downloaded a torrent that has colons and single quotes in the file names. Transmission Remote Gui freezes and I have to kill the process if I click on the file list.

Looking at the same files on a samba share, and the names seem to get translated into random characters.

**Comment by leonsoft-kras** [comment]
what version of TWG freezes?
that shows the web interface transmission, all is correct?

**Comment by tuluse** [comment]
Version 5.5.1

The web interface works fine. It has the same random character display that Windows Explorer has.

**Comment by leonsoft-kras** [comment]
TRG displays information only from a daemon.
If I understand correctly, then the problem is with the characters occurred in the daemon transmission.

**Comment by cfpp2p** [comment]
I confirm issue on v5.5.1, selecting files tab causes freeze (cpu 95%).

On my specialized daemon ( https://github.com/cfpp2p/transmission ), where I'm sure characters are sent by the daemon correctly, I'll still see this behavior with 5.5.1. With my very _highly_ modified TWG (base v3.2.1+) (https://github.com/cfpp2p/transmisson-remote-gui ) the files are displayed normally. I think it is just the colons that are causing the problem.

**Comment by cfpp2p** [comment]
I'm not sure about "_random characters_". Might be related to the daemon's `tr_utf8clean()` which in _official_ daemon  sometimes substitutes with `?`. If I turn that off with this https://github.com/cfpp2p/transmission/commit/a7a259a6fce768f5dda8fa9d7e4df47004bf6c44 TWG 5.5.1 displays blanked file name(s) for such named. But in modified TWG 3.2.1+  display correctly with  `tr_utf8clean()` turned off optionally by https://github.com/cfpp2p/transmission/commit/a7a259a6fce768f5dda8fa9d7e4df47004bf6c44

**Comment by leonsoft-kras** [comment]
Can I get the torrent (or link to it), which causes the freezes TRG?

**Comment by cfpp2p** [comment]
@leonsoft-kras http://transmissionbt.net/colon-quotes-trwo-kinds-test.zip

**Comment by leonsoft-kras** [comment]
thanks)

**Comment by leonsoft-kras** [comment]
I added a simple protection to invalid characters (replace _ ).

**Comment by cfpp2p** [comment]
thank you ;)

**Comment by tuluse** [comment]
Thanks!
