### ISSUE TITLE
Double-clicked in file tab, folder is opened (not file itself)

### ISSUE THREAD

**Issue by bluenlive** [leonsoft-kras/transmisson-remote-gui#936]
When I double-click in file tab, file should be opened.

But, folder is opened.

**Comment by bluenlive** [comment]
In Windows environment,
when user double-click in file tab, file is not opened. Folder is.

maybe following lines(6668..6671) in main.pas causes it.

```{$ifdef mswindows}```
```        p:=Format(FFileManagerDefaultParam, [s]); // ALERT```
```        s:=FFileManagerDefault;```
```{$endif mswindows}```

I believe that lines should be blocked like following.

```{$ifdef mswindows}```
```        //p:=Format(FFileManagerDefaultParam, [s]); // ALERT```
```        //s:=FFileManagerDefault;```
```{$endif mswindows}```

**Comment by leonsoft-kras** [comment]
Have you tried? I made this code to open the files.
Previously, sometimes opened files, but sometimes folders.

**Comment by bluenlive** [comment]
Yes.
This patch made to open file.

**Comment by WROIATE** [comment]
I have the same problem with macOS 10.12 now
