### ISSUE TITLE
Mac OS version 5.6.0: Open / Open containing folder doesn't work with AFP paths

### ISSUE THREAD

**Issue by lvs1974** [leonsoft-kras/transmisson-remote-gui#938]
It worked before upgrade to 5.6.0 (downloaded from this page: https://github.com/leonsoft-kras/transmisson-remote-gui/issues/937)

My path:
/mnt/sdb2/Downloaded=afp://;AUTH=NO USER AUTHENT@dns-325.local/Downloaded

Message Box with error:
Unable to execute "afp://;AUTH=NO USER AUTHENT@dns-325.local/Downloaded/The.Last.Kingdom.S02E05.1080p.rus.LostFilm.TV.mkv".

I also tried the following path:
/mnt/sdb2/Downloaded=afp://dns-325.local/Downloaded

But I get the same error message.

**Comment by leonsoft-kras** [comment]
Set in the ini-file transgui.ini
[interface]
FileOpenDoc=0

Please inform the result

**Comment by lvs1974** [comment]
Thank you, it works!
