### ISSUE TITLE
Remote - Local Path Mapping

### ISSUE THREAD

**Issue by pranavt** [leonsoft-kras/transmisson-remote-gui#939]
Can someone please help with the path mapping?

transmission-daemon running on a Linux box. Files to be stored in /media/downloads

Client running on a Windows box. Paths mapped as either:
\\\dBox\downloads (/media/downloads)
or
Y:\downloads (remote drive mapped)

Putting this does not work:
/media/downloads = Y:\downloads
or
/media/downloads = \\\dBox=downloads

The usual error: Unable to find path mapping. Use the application's options to setup path mappings.

Please tell me where I'm wrong and what the correct way to fix it is. Thanks!

**Comment by leonsoft-kras** [comment]
My simple settings:
/tmp/mnt/TRANS/soft=\\192.168.1.9\soft

left = transm.daemon
right = network path (The \\ 192.168 .. folder must be accessible over the network. Please check from the Explorer.)

**Comment by pranavt** [comment]
*facepalm*

Not putting spaces before/after the = sign fixed the issue.
