### ISSUE TITLE
Arch Linux - Chrome: magnet links open transmission gui via xdg-open but do not show "add dialog"

### ISSUE THREAD

**Issue by KGCybeX** [leonsoft-kras/transmisson-remote-gui#940]
Hi

Thanks for the great software, a small issue:

**Problem:**

When opening magnet links from Chrome, it open Transmission Remote GUI but no popup dialog to add the magnet appears, this I am required to either:

1. Copy magnet link to clipboard
2. Manaully add magnet via menu 
3. Download the `.torrent` file and open it

all the above open the "add dialog" as required.

**Note:**

I am convinced it may be an issue on my part - some small setting in Arch but the fact that it opens Transmission Remote GUI implies that it must be an issue with:
 - handing the link to T.R.G - maybe a clipboard issue, or
 - link not parsed properly, or 
 - listener not triggering (just guessing)

but I am reporting it for the sake of it.

_Note:_ `.torrent` files open Transmission Remote GUI and show `add torrent` dialog

*Previous version was downloaded via Arch AUR with [git link](https://github.com/leonsoft-kras/transmisson-remote-gui) - last updated version was _2017-01-04 @ 22:42_

Some info:

- Chrome - Version 58.0.3029.81 (64-bit)
- Transmission Remote GUI - Version 5.6.0
- Gnome-Shell - 3.22

**Comment by frangi** [comment]
it's definitely on your part, I just tested it and it works.

I'm the maintainer of: https://aur.archlinux.org/packages/transmission-remote-gui-bin/
you probably have a faulty desktop file, you can check the one included in the package above.
