### ISSUE TITLE
Can't type [ and similar characters when renaming a torrent

### ISSUE THREAD

**Issue by Diskutant** [leonsoft-kras/transmisson-remote-gui#947]
When renaming a torrent (contextmenu - Rename, or F2) I can't type [, ], |
Instead it switched to active, inactive, stopped etc.

Might be because on german keyboard those characters are typed using alt+5 for [, alt+6  for ] and alt+7 for |

macOS 10.12.5
Transmission Remote 5.6.0
German keyboard layout

I think hotkeys should be disabled while in a typing field.

**Comment by antekgla** [comment]
@leonsoft-kras that is my fault :disappointed:
In my version of Transmission 2.61 the rename function is not allowed, besides in my spanish keyboard layout the Alt+(Number) dont fires any special character.
To solve this you have to change the line #3892 of main.pas to this:

`     if (Shift = [ssAlt]) and not (MainForm.ActiveControl is TVarGridStringEditor) then`

Sorry for the inconvenience.

**Comment by leonsoft-kras** [comment]
thanks you! ))
fix
