### ISSUE TITLE
About 5.6 Release

### ISSUE THREAD

**Issue by antekgla** [leonsoft-kras/transmisson-remote-gui#948]
Hi @leonsoft-kras !
...first of all thank you for implement my improvements in your release 👍 

However maybe this improvements could be missing to the general public because are not in the GUI but by modifying the file _transgui.ini_, so in my opinion would be good document this somewhere.
I think what the best place is the readme, but that is your choice.
This is my sugestion (**bold parts are now in the readme**):

>..
>**PORTABLE MODE
> If the program finds the transgui.ini file in the same folder as the binary file, then it will store all configuration and data files in the program's folder, instead of the folder in a user profile.**
>
>FIXED SHORTCUTS
>
>Alt + 1 : All Torrents
>Alt + 2 : Downloading
>Alt + 3 : Completed
>Alt + 4 : Active
>Alt + 5 : Inactive
>Alt + 6 : Stopped
>Alt + 7 : Error
>Alt + S : Searchbox (filter torrents by keywords) - Esc cancel filter and clean the box.
>Alt + G : Info Pane - General Tab
>Alt + K : Info Pane - Trackers Tab
>Alt + P : Info Pane - Peers Tab
>Alt + F : Info Pane - Files Tab
>
>
>**ADVANCED PARAMETERS**
>
>**There are some parameters in the transgui.ini file, that can not be modified via the GUI.**
>More info on: https://github.com/leonsoft-kras/transmisson-remote-gui/issues/924
>
>**[Interface]
>; Maximum number of elements in the folder history list
>MaxFoldersHistory=10**
>
>
>[Interface]
>;Alternate File Manager (Windows Only)
>FileManagerDefault={Full path to your File FileManager .exe}
>FileManagerDefaultParam={Alternate parameters, could be left blank}
>
>[Interface]
>;System Wide Shortcut key (Windows Only)
>GlobalHotkey={Virtual Key Code} full list here http://docwiki.embarcadero.com/RADStudio/Seattle/en/Virtual_Key_Codes (Plus VK_A...VK_Z and VK_0..VK_9)
>GlobalHotkeyMod={Modifier Key} [MOD_SHIFT , MOD_CONTROL , MOD_ALT , MOD_WIN alone or combined with + sign]
>
>[Shortcuts]
>;Modify all the shortcuts of the GUI here

Also I modified the routine of the customization of the shortcuts of the GUI for in the case of non existence of [Shortcuts] section in the transgui.ini the program generate this section with the default shortcuts. This new routine only fires if the Shortcuts section dont exist so it mean to be executed only one time.
You have to change this on line 1581:
```Pascal
  //Dynamic Associations of ShortCuts to Actions/Menus
  SL := TStringList.Create;
  try
  Ini.ReadSectionValues('ShortCuts', SL);
  for i := 0 to SL.Count - 1 do
        TAction(ActionList.ActionbyName('ac'+SL.Names[i])).ShortCut:=TextToShortcut(SL.ValueFromIndex[i]);
  finally
    SL.Free;
  end;   
```

to this:

```Pascal
  //Dynamic Associations of ShortCuts to Actions/Menus
  SL := TStringList.Create;
  try
    Ini.ReadSectionValues('ShortCuts', SL);
    if SL.Text = ''  then
      begin
          for i := 0 to ActionList.ActionCount-1 do
          Ini.WriteString('Shortcuts',StringReplace(ActionList.Actions[i].Name,'ac','',[]),ShortcutToText(TAction(ActionList.Actions[i]).ShortCut));
      end
      else
         for i := 0 to SL.Count - 1 do
              try
                  TAction(ActionList.ActionbyName('ac'+SL.Names[i])).ShortCut := TextToShortcut(SL.ValueFromIndex[i]);
              except
              end;
  finally
    SL.Free;
  end;
```

Cheers!

**Comment by leonsoft-kras** [comment]
Hi Antekgla,
Can you correct the files yourself, check and fix them? 
I have long given you the right to edit.

thanks you

**Comment by antekgla** [comment]
OK, done via web (readme and main.pas)
As I say I never use Github before so I am afraid of break something.

I think what I do it right but please when you have some time, check it yourself.
Thanks again!
