### ISSUE TITLE
TLS on MacOS is broken

### ISSUE THREAD

**Issue by PeterDaveHello** [leonsoft-kras/transmisson-remote-gui#950]
Hi there,

Thanks a lot for this awesome tool, it helps a lot!

I just found a small issue here, the release for MacOS seems to use SSLv3 to communicate with my server which is https enabled with TLS support but SSLv3 disabled for security reason, this problem doesn't exist on my Windows client, they are both v5.6, the error message is captured as below, please let me know that if there is anything I can do to help locate the problem, thanks!

![image](https://cloud.githubusercontent.com/assets/3691490/26765983/0b19477a-49ba-11e7-8519-1aae5f4a1cd1.png)

PS:
My MacOS version: 10.12.5

**Comment by k0ste** [comment]
Try to apply [this](https://github.com/leonsoft-kras/transmisson-remote-gui/issues/941#issuecomment-298150227) patch.

**Comment by PeterDaveHello** [comment]
@k0ste any chance to send a pull request so that the official build can include it? Thanks a lot.

**Comment by k0ste** [comment]
I can easy make PR, but this patch should be reviewed, may be by @leonsoft-kras. Because this is hack, actually I'm not sure of its correctness.

**Comment by leonsoft-kras** [comment]
I suggest in the ini-file to create a key for enabling / disabling protocols. 
It's better than generally removing the support for other versions of the protocols. 
Someone will approach one option, someone else.

I can not verify this code. For macos especially.
If this change is good - this setting can be made in the program settings

**Comment by PeterDaveHello** [comment]
As SSLv3 was confirmed not secured anymore for a while, I'll respectfully suggested to just remove it, the options can be prepared for TLS v1.0~v1.3 only, thanks!

**Comment by leonsoft-kras** [comment]
Removed support for SSL2, SSL3 as unsafe.
thanks!

**Comment by PeterDaveHello** [comment]
Thanks @leonsoft-kras, may I ask if there is any plan on the next release?

**Comment by leonsoft-kras** [comment]
There are minor problems with Linux and it seems like a switch to Lazarus 1.6.4.
I hope that soon.

**Comment by leonsoft-kras** [comment]
Please see Issue #962

**Comment by PeterDaveHello** [comment]
Should be fixed in #963

**Comment by PeterDaveHello** [comment]
Still not working yet.

**Comment by PeterDaveHello** [comment]
https://github.com/leonsoft-kras/transmisson-remote-gui/releases/tag/v5.8.0

![default](https://user-images.githubusercontent.com/3691490/27913108-a4229c4c-6291-11e7-9f90-dacd8bb8cca7.png)

![default](https://user-images.githubusercontent.com/3691490/27913105-9d4e274c-6291-11e7-9390-cd65ffe1d94f.png)

**Comment by leonsoft-kras** [comment]
I now corrected the history file and the project file in version 5.8 (in several places it was necessary to write about version 5.8). Version for Windows already with the fix.

**Comment by PeterDaveHello** [comment]
@leonsoft-kras I'll build Raspberry Pi and Linux i386 release soon, MacOS release still has problem with TLS support however.

**Comment by leonsoft-kras** [comment]
This problem exists only in MacOS or is it still common for any operating system?

**Comment by PeterDaveHello** [comment]
I think it's Mac only.

**Comment by PeterDaveHello** [comment]
It's working on macOS 10.13, so maybe it's a bug from os or other level.
