### ISSUE TITLE
App icon not showing in Linux

### ISSUE THREAD

**Issue by spvkgn** [leonsoft-kras/transmisson-remote-gui#951]
App icon is missing and tray icon as well. Can you please take a look into this issue?
![default](https://user-images.githubusercontent.com/4147135/27008621-f5de2daa-4e8f-11e7-8e5d-51370dbe2cf4.png)
Ubuntu 17.04 x86_64

**Comment by ricrogz** [comment]
I just uploaded a pull request to fix this :)

**Comment by didli** [comment]
Same problem here in Fedora 25 x64 with xfce : no tray icon with latest release 5.6

**Comment by leonsoft-kras** [comment]
Soon there will be a distribution

**Comment by k0ste** [comment]
Fixed in 5.7.0.
