### ISSUE TITLE
How to use domain name without filling the port?

### ISSUE THREAD

**Issue by zhengxinhn** [leonsoft-kras/transmisson-remote-gui#954]
I use transmission and Aria2 on my router ,but i don`t have a public network IP .
So i have to use frp (A fast reverse proxy to help you expose a local server behind a NAT or firewall to the internet.) https://github.com/fatedier/frp 
It can direct a domain name to my local ip and local port.
It looks like the transmission has something similar with Aria2.
When i use Aria2 in  to download in LAN,the rpc address is http://192.168.123.1:6800/jsonrpc.
Internet  access just chang it  to http://***.domainname.***/jsonrpc  will be able to work.
Transmisson-remote force to fill out remote host and port makes connection refused.

**Comment by leonsoft-kras** [comment]
You understand the situation?

**Comment by zhengxinhn** [comment]
Yes,specify port 80 works fine,another way is to open a remote port at server.
I am lacking in this knowledge.
