### ISSUE TITLE
TLS support on Raspberry Pi build

### ISSUE THREAD

**Issue by PeterDaveHello** [leonsoft-kras/transmisson-remote-gui#956]
Using v5.6.0 on Raspberry Pi 3, Raspbian, when I trying to download the country flags, it told me `SSL/TLS support is not compiled`, is it possible to enable that on the Raspberry Pi build? Thanks a lot!

**Comment by leonsoft-kras** [comment]
In the description of version 5.6 "In the Installation for downloading SSL libraries added Visual Redistributable Package (For pure Windows systems). For Linux install manually libssl-dev.
I don't know how to implement the library in Linux. You must manually type "
sudo apt-get install libssl-dev"
:)

**Comment by PeterDaveHello** [comment]
Thanks for the prompt response @leonsoft-kras! 
I installed `libssl-dev` package now, and now I can't tell what the problem is, mind to take a look? Thank you for your time!

![default](https://user-images.githubusercontent.com/3691490/27521856-d396f342-5a53-11e7-9642-d5808512edd9.png)

**Comment by Snegohod** [comment]
@PeterDaveHello see this [issue](https://github.com/leonsoft-kras/transmisson-remote-gui/issues/941)
What version of openssl and libssl-dev you installed?

**Comment by PeterDaveHello** [comment]
@Snegohod 1.1.0f-3, from Raspbian Jessie, thank you.
