### ISSUE TITLE
Request: per-torrent speed limits

### ISSUE THREAD

**Issue by inspector71** [leonsoft-kras/transmisson-remote-gui#957]
Per-torrent speed limits would be a great addition to this very good program.

**Comment by leonsoft-kras** [comment]
Files download transmissions.
TRGUI implements only what allows the transmissions.

**Comment by PeterDaveHello** [comment]
Isn't this a native feature in transmission that not directly related with this project?

**Comment by leonsoft-kras** [comment]
I don't have such a function in my web client transmission

**Comment by PeterDaveHello** [comment]
Sorry that I misunderstood, I thought it's already supported?

![default](https://user-images.githubusercontent.com/3691490/27874287-9256f61c-61e1-11e7-9eb1-16fd4a5382b9.png)

**Comment by leonsoft-kras** [comment]
In my web interface there is no such.
If someone adds such a function to the TRGUI and checks it - welcome)

**Comment by PeterDaveHello** [comment]
The screenshot is from TRGUI, so what else we should do?

**Comment by leonsoft-kras** [comment]
My TRGUI does not show such a dialogue.
I did not know about such a function.

**Comment by PeterDaveHello** [comment]
I just got it when I double click on a torrent.

**Comment by leonsoft-kras** [comment]
I'm an old stump. Forgot about this))
There really is such a function.

**Comment by PeterDaveHello** [comment]
@inspector71 can you confirm please?

**Comment by inspector71** [comment]
Thanks. I'll check in around 8 hrs.

Perhaps a new issue, our meta issue, i'd on the horizon: implement
per-column, task-relevant context menus.

I've not been using TRGUI for very long but I've found its similarity to
utorrent circa version 1.8 to 2.1, roughly, very handy. Adding per-column,
task-relevant, context menus would be a great further step down that road.



On 7 Jul 2017 12:46 AM, "Peter Dave Hello" <notifications@github.com> wrote:

@inspector71 <https://github.com/inspector71> can you confirm please?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/leonsoft-kras/transmisson-remote-gui/issues/957#issuecomment-313418178>,
or mute the thread

**Comment by inspector71** [comment]
OK, confirmed! Thanks everyone!
