### ISSUE TITLE
Compilation MacOS version

### ISSUE THREAD

**Issue by leonsoft-kras** [leonsoft-kras/transmisson-remote-gui#958]
For compilation version please write here. 
Fortunately, I don't have this operating system. I can't do the distribution myself.  
The version for the MacOS is compiled by a colleague. He needs time.

**Comment by PeterDaveHello** [comment]
I can help do that if you want :)

**Comment by PeterDaveHello** [comment]
Using Travis CI to build and deliver the releases based on git tag may be a better solution!

**Comment by leonsoft-kras** [comment]
PeterDaveHello, now you can make a distribution for Mac and add to the releases ))

Any help from everyone is accepted!

**Comment by PeterDaveHello** [comment]
Cool, I'll take a look at the compilation process on MacOS later!

**Comment by ijaureguialzo** [comment]
This might help: https://github.com/nielsAD/travis-lazarus

**Comment by ijaureguialzo** [comment]
I did an experiment (#961) with Travis CI on macOS and it's working.

**Comment by leonsoft-kras** [comment]
Maybe PeterDaveHello will evaluate the revision and add your edits to the githab

**Comment by PeterDaveHello** [comment]
I'll first figure out how should I do that on my Mac :)

**Comment by ijaureguialzo** [comment]
For those in need like me, here's the Travis compiled version for macOS: https://github.com/ijaureguialzo/transmisson-remote-gui/releases/tag/5.7.0

It's built automatically from the source.
