### ISSUE TITLE
Is "No commit message" a bug?

### ISSUE THREAD

**Issue by PeterDaveHello** [leonsoft-kras/transmisson-remote-gui#959]
No offense, not sure if those commits with `No commit message` commit message is a bug? Just trying to get involved and start to trace the changes. Thanks.

**Comment by leonsoft-kras** [comment]
There are mistakes and wishes. Wishes are useful and useless (for me and perhaps many). I am not ready to do any useless wishes, because the program is free and I'm not ready to spend my evenings on the introduction of incomprehensible functions.

**Comment by KottV** [comment]
@leonsoft-kras не могли бы вы ответ на русский перевести?:)

**Comment by leonsoft-kras** [comment]
На бесполезные предложения у меня нет ни времени ни желания. Я понимаю, что не каждое обращение - это баг. Но среди "багов" много бесполезного..

**Comment by KottV** [comment]
Ну речь же не про предложения.
Товарищ спрашивал: "почему ваши коммиты не подписаны?" он хотел бы влиться в разработку и понять, что эти коммиты дают. Без наездов.

**Comment by leonsoft-kras** [comment]
Значит писать надо подробнее и проще ))

**Comment by KottV** [comment]
По-моему какое-то недопонимание =/
Мне, например, тоже неудобно отслеживать изменения в проекте  из-за неподписанных коммитов (я собираю пакеты: https://software.opensuse.org/search?utf8=%E2%9C%93&q=transgui&search_devel=false&search_unsupported=false&baseproject=ALL), а там могут быть важные баги фикситься.

**Comment by leonsoft-kras** [comment]
предпочитаю комменты в коде. что и как прописано в этих комментах... большой вопрос. 
возможно кому-то чтение комментов что-то дает. в моем опыте - не особо. 

на эту тему можно долго дискутировать, поэтому стоп. при очередном фиксе возможно заполню коммент. правда не уверен, что мой английский поможет другим разработчикам разобраться в важности данного фикса.
