### ISSUE TITLE
Linux binaries for 5.7

### ISSUE THREAD

**Issue by peaveyman** [leonsoft-kras/transmisson-remote-gui#960]
I see there is a linux zip build here: https://github.com/leonsoft-kras/transmisson-remote-gui/releases/download/v5.7.0/transgui-5.7-i386-linux.zip

Will there be a x86_64 build?

**Comment by peaveyman** [comment]
I have these built. How can I get it to you?

**Comment by Snegohod** [comment]
@peaveyman add binary https://github.com/leonsoft-kras/transmisson-remote-gui/releases/download/v5.7.0/transgui-5.7-x86_64-linux.zip
