### ISSUE TITLE
TLS 1.2 support broken in v5.7

### ISSUE THREAD

**Issue by ApexWeed** [leonsoft-kras/transmisson-remote-gui#962]
Hi,

v5.7 no longer connects to either of my TLS 1.2 enabled servers running transmission behind an nginx reverse proxy (ip filtering etc). Relevant urls are https://helifreak.club and https://kasko.helifreak.club as its the same TLS config.

Relevant nginx config is as follows:
```
ssl_stapling on;
ssl_stapling_verify on;
ssl_trusted_certificate chain.pem;
add_header Strict-Transport-Security max-age=15768000;
add_header X-Content-Type-Options nosniff;
add_header X-Frame-Options SAMEORIGIN;
add_header X-XSS-Protection "1; mode=block";
ssl_session_timeout 1d;
ssl_session_cache shared:SSL:50m;
ssl_session_tickets off;
ssl_protocols TLSv1.2;
ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
```

First connect gives the following error:

error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version

Switching to another server changes the error to:

Network subsystem is unusable

Reverted back to v5.6 in the meantime until this is fixed.

**Comment by k0ste** [comment]
Try:
```
ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
```

**Comment by PeterDaveHello** [comment]
`TLSv1.3` is not officially released and not wildly support in most of the nginx versions, better not to add that.

**Comment by k0ste** [comment]
@PeterDaveHello, of course.

But, we actually don't kwon what is @ApexWeed openssl client and server libraries version.

**Comment by ApexWeed** [comment]
Doesn't work with any combination of TLSv1 - TLSv1.3. Client openssl version is 1.0.2.10 that comes with the Windows installer, updated it to a 1.0.2.12 build and the same thing happened. Servers are running the following versions (nginx compiled from source for extension support):
Arch 64 bit, nginx/1.13.1, OpenSSL 1.1.0f  25 May 2017
CentOS 7.2, nginx/1.13.0, OpenSSL 1.0.1e-fips 11 Feb 2013

**Comment by k0ste** [comment]
You should update your client to openssl 1.1.0.

**Comment by ApexWeed** [comment]
Where do I get that? https://indy.fulgan.com/SSL/ only goes up to 1.0.2.12

**Comment by PeterDaveHello** [comment]
I don't think it's a server side problem but a client issue.

**Comment by PeterDaveHello** [comment]
Hope 87b9925a328d034cb387d2d906c098de4a645351 in #963 would fix it.

**Comment by leonsoft-kras** [comment]
Excellent!!!
What version to compile for the test - Windows or Linux?

**Comment by ApexWeed** [comment]
I'm on Windows, unless there's someone else on Linux that had the same issue.

**Comment by leonsoft-kras** [comment]
please try https://yadi.sk/d/cth0FUUm3KmsJc
Let us know the results

**Comment by ApexWeed** [comment]
Doesn't appear to have fixed it unfortunately. With nginx configured to accept TLS v1-1.3 I get
error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
With it configured to only accept v1.2-1.3 I get
error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version
Doesn't work with SSLv3 enabled either which makes sense.

**Comment by leonsoft-kras** [comment]
Smart heads will continue to seek a solution.

**Comment by k0ste** [comment]
Somebody test #966 patch.
The main issue is my dirty hack from [here](https://github.com/leonsoft-kras/transmisson-remote-gui/issues/941#issuecomment-298150227). I warned that the patch needs to be reviewed.

**Comment by leonsoft-kras** [comment]
try https://yadi.sk/d/XenvS-vu3Kmyz5

**Comment by ApexWeed** [comment]
Yep, that did it. Thanks.

**Comment by PeterDaveHello** [comment]
Well ... I believe that it's not fixed yet:
https://github.com/leonsoft-kras/transmisson-remote-gui/releases/tag/v5.8.0-test

![default](https://user-images.githubusercontent.com/3691490/27913108-a4229c4c-6291-11e7-9f90-dacd8bb8cca7.png)

![default](https://user-images.githubusercontent.com/3691490/27913105-9d4e274c-6291-11e7-9390-cd65ffe1d94f.png)

**Comment by GRArmstrong** [comment]
@leonsoft-kras @ApexWeed I don't suppose either of you two could share what was behind that link, could you please? I'm stuck on a very similar issue.

**Comment by leonsoft-kras** [comment]
> @leonsoft-kras @ApexWeed I don't suppose either of you two could share what was behind that link, could you please? I'm stuck on a very similar issue.

I do not remember. it seems I have updated the SSL support in the project. In this project, a library is used and something has been removed / added in it.
