### ISSUE TITLE
Provide portable version of Windows release.

### ISSUE THREAD

**Issue by elisimpson** [leonsoft-kras/transmisson-remote-gui#973]
Most Windows EXEs allow the user to extract the contents without actually running the installer. TRG currently doesn't allow this, forcing the user at least temporarily to install the program to get access to the new files.

Desired result: easier way to use TRG as a portable app without an install on Windows.

**Comment by leonsoft-kras** [comment]
And what is the difference, or what is the difficulty?
1. Download the installer, run, click 5 times "next".
2. Download the archive with the program, start the archiver, press 5 times "next".

**Comment by elisimpson** [comment]
The goal is to not have to install it. Many Windows users don't like to (or can't) install programs in the traditional way. They just want to extract the files to a folder of the their choice and run the program directly. You can do this buy providing a ZIP version of the files (not of the installer, but the files the installer eventually extracts to). Or just make the EXE so it can be extracted by common tools like 7zip or WinRAR.

**Comment by PeterDaveHello** [comment]
I think we can just provide portable tarball for Windows, I double that most of the exe files can be extract directly ...

**Comment by elisimpson** [comment]
That would be great! I was able to extract the necessary files with a specialized tool (Universal Extractor) but an official portable version would be optimal and appreciated.

**Comment by PeterDaveHello** [comment]
I mostly use Linux, seldom on macOS and Windows, so wouldn't work on this so soon. Not sure if @leonsoft-kras would like to do that, I'm good with it.

**Comment by leonsoft-kras** [comment]
Me and very MANY other users are satisfied with the installer of the program for Windows. )))

I'm not against adding a version of the program for windows in a zip archive. But for this we need to create a script that will automatically collect many files into the archive. I can not say when this script will be written

**Comment by PeterDaveHello** [comment]
@elisimpson I released v5.8.2 with zip here: https://github.com/leonsoft-kras/transmisson-remote-gui/releases/tag/v5.8.2, let me know if there is anything else should be done.

**Comment by leonsoft-kras** [comment]
I understand the compilation for Windows is no longer needed?

**Comment by PeterDaveHello** [comment]
@leonsoft-kras depends on you.

**Comment by leonsoft-kras** [comment]
So the version already exists in the releases. I did not have time to do it before. Someone has already done this for me.

**Comment by PeterDaveHello** [comment]
I did it. I mean the future release, the installer is needed or not, depends on you, I'm fine with that.
