### ISSUE TITLE
No Windows release for 5.8.1

### ISSUE THREAD

**Issue by stsmurfy** [leonsoft-kras/transmisson-remote-gui#983]
The program says there is a new update (5.8.1), but I can't find in the download page.

![image](https://user-images.githubusercontent.com/25842875/28365796-4085285a-6c8a-11e7-8df3-92e7ee076fa6.png)

![image](https://user-images.githubusercontent.com/25842875/28365783-324e711a-6c8a-11e7-9fc1-820c98440ac4.png)

**Comment by leonsoft-kras** [comment]
Refresh page please
