### ISSUE TITLE
Show global bandwidth limits in status bar

### ISSUE THREAD

**Issue by scporse** [leonsoft-kras/transmisson-remote-gui#993]
As the title says, I would really like an option to have the currently selected global bandwidth limits shown in the bottom status bar.
![untitled](https://user-images.githubusercontent.com/30633152/28838413-8c05869c-76f0-11e7-9bcf-e72c74a6c3b6.png)

**Comment by antekgla** [comment]
Done! https://github.com/leonsoft-kras/transmisson-remote-gui/commit/55d93fafde05c32f04cf709855a4e4ef2caa3005

Now in Status Bar next to Global Download & Upload limits are (between parenthesis) their corresponding limits.

![limits](https://user-images.githubusercontent.com/24402722/32458283-ae4a6838-c30a-11e7-8e8e-0a3646357d75.jpg)
