### ISSUE TITLE
[question] Where are (linux) download links ?

### ISSUE THREAD

**Issue by quazardous** [leonsoft-kras/transmisson-remote-gui#995]
Hi,

I used to dl from SF but version is outdated.
where can I find the binaries for linus ?

thx

**Comment by bluehangel** [comment]
https://github.com/leonsoft-kras/transmisson-remote-gui/releases

**Comment by scporse** [comment]
I was wondering about that too. Is this repository a fork of the [version on sourceforge](https://sourceforge.net/projects/transgui/)? In any case, it's sort of unfortunate that the top hit you get when googling "transgui", points to the rather outdated version on Sourceforge.

**Comment by leonsoft-kras** [comment]
This project develops independently and has no relation to the author of the program.

The original version of the program 5.0.1 is placed on the sourforge. 
It is probably supported by the author of the program.

**Comment by scporse** [comment]
Right then. That clears things up quite a bit - at least to me.
Then I do hope that eventually your project will receive more hits than the counterpart, allowing it to climb to the top of search results, as it clearly seems to be the most well-maintaned Transmission remote GUI application.

**Comment by quazardous** [comment]
thx for the link but where did you find it ? (more a general github question)

**Comment by scporse** [comment]
@quazardous 
I'm not sure exactly what you mean. If you're referring to how first stumbled upon the old version on SourceForge, then all I did was google the term 'transgui' where the top 2 hits in this search point to SF. The same thing happens when googling 'transmission remote gui'.

**Comment by bluehangel** [comment]
@quazardous
Root of the Github project, code tab, Release section close to commits and branches.

**Comment by quazardous** [comment]
I feel so dumb but at least I got an answer :/
