### ISSUE TITLE
Add several torrent/magnet files at once

### ISSUE THREAD

**Issue by ffries** [leonsoft-kras/transmisson-remote-gui#999]
Hello,

I usually support free software communities running transmission remote with for example:
https://www.funkthat.com/~jmg/FreeBSD-11.0-R-magnet.txt.asc

This is hard to add all files one by one.

Would it help if it was possible that transmission-remote-gui was able to parse a remote file and look for embedded magnets or torrents.

The same issue was submitted to main transmission software, but I am using transmission-remote-gtk.

Kind regards,

**Comment by forsomefun** [comment]
You can already add a bunch of torrent files if you have them downloaded already. 
Unfortunately, the program glitches on window even when adding 20 of them.

Though I have to say it is very cool to see it working. When this is not a problem. 
Not sure what is causing these memory leaks.

**Comment by antekgla** [comment]
I only have to un-check **"Prompt for download options when adding a new torrent"**.
Now from 5.11 the checkbox Start Torrent is remembered so you can add several torrents/magnet in stopped state without any window asking anything.
If you un-check that option and copy several magnets to the clipboard, they would be added right away.
